### ISSUE TITLE
4k Resolution

### ISSUE THREAD

**Issue by mmaarrccooo** [eliemichel/MapsModelsImporter#10]
Are there any experiences with high resolutions?

I've tested the latest version with Chromium 61.0 64bit portable (current Chrome 76 did not work) and RenderDoc 1.1 (64 bit) portable.

Hardware/Software: Dell XPS (2014), forced dedicated GeForce 750M to be used with Chromium (v61.0), Windows 10

The notebook has a native resolution of  3840 x 2160.

- MapsModelsImporter / RenderDoc did work with a Windows display zoom/scaling of 200%. Everything okay. (file size ~74mb). Import with Blender 2.80 works.
- MapsModelsImporter / RenderDoc did NOT work with a display zoom of 100% (native resolution). RenderDoc seems to produce correct data (events in Texture Viewer are okay). Blender 2.80 tried to import the file (130mb) for some time but in the end, the scene was still empty :/

Did anyone tried this kind of high resolution before?

BTW: Also successfully tested latest MapsModelsImporter + RenderDoc 1.1 + GeForce GTX 1050 Ti @1920x1080 + Windows 10 + Blender 2.80 + Chromium 61.0

**Comment by eliemichel** [comment]
Did you have any error message in the console? I've successfully imported captures with a zoom of 50% on my HD screen, around 150Mo. It took a while but succeeded. Take care of increasing the limitation of imported blocks when browsing for the capture file. It defaults to 200 to prevent it from hanging too long for new users, but on such large captures you can set it to like 999999. Maybe the 200 imported objects are just out of sight, have you checked the outliner?
