### ISSUE TITLE
Issue: Cannot import RDC file

### ISSUE THREAD

**Issue by sg4444** [eliemichel/MapsModelsImporter#101]
Error importing RDC file in Blender:

Invalid RDC capture file. Please make sure that:
1. You are importing from Google Maps (NOT Google Earth)
2. You were MOVING in the 3D view while taking the capture (you can use the Capture after delay button in RenderDoc).

 - The .rdc file: [lake kaindy 2.zip](https://github.com/eliemichel/MapsModelsImporter/files/5411481/lake.kaindy.2.zip)
 - Your GPU name: intel uhd graphics 620
 - Version of this add-on (must be the most recent one): v.0.3.2
 - Version of RenderDoc (1.9 recommended, do not use v1.10): 1.9
 - Version of Blender (2.82 minimum): 2.90.1

Console log from blender:

found bundled python: C:\Program Files\Blender Foundation\Blender 2.90\2.90\python
Writing userprefs: 'C:\Users\xx\AppData\Roaming\Blender Foundation\Blender\2.90\config\userpref.blend' ok
Info: Deleted 1 object(s)

addon_utils.disable: MapsModelsImporter not disabled
Modules Installed (MapsModelsImporter) from 'C:\\Users\\xx\\Downloads\\MapsModelsImporter-v0.3.2.zip' into 'C:\\Users\\xx\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons'
globUniforms:
  _sk_RTAdjust: [0.010416666977107525, -1.0, 0.03125, -1.0]
  _ulocalMatrix_Stage0: [1.0, 709.0, 1.0, -0.0]
  _umatrix_Stage1_c0_c0: [0.007462686393409967, 0.0, 0.0, 0.0, 0.0005324813537299633, 0.0, -5.29104471206665, 0.19329072535037994, 1.0]
globUniforms:
  _sk_RTAdjust: [0.010416666977107525, -1.0, 0.03125, -1.0]
  _ulocalMatrix_Stage0: [1.0, 709.0, 1.0, -0.0]
  _umatrix_Stage1_c0_c0: [0.007462686393409967, 0.0, 0.0, 0.0, 0.0005324813537299633, 0.0, -5.29104471206665, 0.19329072535037994, 1.0]
globUniforms:
  _b: [14.0625, 7.03125, -8.0, -1.0]
  _e: [-1.402893304824829, -29.097139358520508, 97.46917724609375, 97.46917724609375, -124.34675598144531, 10.589407920837402, 0.7114924192428589, 0.7114924192428589, 10.079248428344727, 126.59062194824219, 22.343990325927734, 22.343990325927734, -6.79052902796684e-08, -1.627659074188159e-08, -0.6666666269302368, 1.450032272032331e-07]
globUniforms:
  _b: [14.0625, 7.03125, -0.0, -1.0]
  _e: [-32.4459228515625, -46.57317352294922, 78.23231506347656, 78.23231506347656, -54.571533203125, 35.72068786621094, -43.432373046875, -43.432373046875, 3.7661969661712646, 116.35693359375, 44.646766662597656, 44.646766662597656, -2.9210813323743423e-08, 1.4352757204960653e-08, -0.6666667461395264, -8.798961559364216e-10]
globUniforms:
  _b: [14.0625, 7.03125, -0.0, -1.0]
  _e: [-32.4459228515625, -46.57317352294922, 78.23231506347656, 78.23231506347656, -54.571533203125, 35.72068786621094, -43.432373046875, -43.432373046875, 3.7661969661712646, 116.35693359375, 44.646766662597656, 44.646766662597656, -2.9210813323743423e-08, 1.4352757204960653e-08, -0.6666667461395264, -8.798961559364216e-10]

I am out of options now, what can I try?
Thanks.

**Comment by eliemichel** [comment]
You captured an image from street view. Google Maps does not use 3D for streetview (well, it does, but the 3D scene is just a sphere with pictures projected on it in that case) so there is no information about the relief here, you must capture the rdc while being in 3D mode instead.
