### ISSUE TITLE
problems with it :(

### ISSUE THREAD

**Issue by alexg030** [eliemichel/MapsModelsImporter#102]
hello sadly i have a problem 
i have all the things that are required and everything worked.
I have the addon in Blender and a ready file from renderdoc. but sadly when i try to import it blender just does nothing, not even an error notification.:( would be wonderful if somebody could help me cheers

**Comment by eliemichel** [comment]
Did you close this because you solved it? You can turn on debug info in the addon's preferences and then look into the system console after trying to import an RDC file (Window > Toggle System Console)

**Comment by alexg030** [comment]
yeah everything worked out thank you sooo much

Am Mi., 21. Okt. 2020 um 22:47 Uhr schrieb Elie Michel <
notifications@github.com>:
