### ISSUE TITLE
Error with RDC

### ISSUE THREAD

**Issue by starman78** [eliemichel/MapsModelsImporter#106]
I've still have the problem. Blender report to the same issue : " Invalid RDC capture file. Please make sure that...1.....and 2..."

I've tried do downgrade RenderDoc from 1.10 to 1.9
I've the lastest version of this Add-on

Pls could someone provide any suggestions? Tks

 - Version of this add-on (0.33-rc1
 - Version of RenderDoc (1.9)
 - Version of Blender (2.890.1 minimum)

[Documents.zip](https://github.com/eliemichel/MapsModelsImporter/files/5446342/Documents.zip)

**Comment by starman78** [comment]
Blender Version 2.90.1

**Comment by eliemichel** [comment]
Hi @starman78 
There is no 3d information in this capture file:
![image](https://user-images.githubusercontent.com/5802849/97357376-f8e8c780-1899-11eb-83f4-e0a1081f59c8.png)
 A valid capture contains much more draw calls and each draws much more than 30 vertices.
Either you were not moving in the viewport while taking the capture (for instance using the Capture After Delay button) or you should consider taking 2 or 3 sequential frames and keeping the one that has 3d in it:

![image](https://user-images.githubusercontent.com/5802849/97357532-39484580-189a-11eb-9634-1d3eb9b1e8f6.png)

**Comment by maximiac** [comment]
I have the same problem, I cant take any frame right, i use 3 or 4 sequential frames after delay of some seconds so I have time to move my mouse, while frames are capturing the view freezes and the rseult is always with only 4 draw calls and I cant import in blender... can anyone do a snap of the location I would like to import for me? xD  42.472383, 14.209629

**Comment by eliemichel** [comment]
Does using Microsoft Edge instead of Chrome work for any of you? Still using the custom shortcut, but replacing the path to chrome.exe by the one to edge instead (Edge is derived from Chromium too)

**Comment by GeorgeD80** [comment]
Hi Elie,

i have the same problem, i tried Edge with the same custom shortcut but with the edge path instead. Unforunately it does not find the application. I am using  the Graphics-Card:
AMD Radeon R9 380
Could it be related to that?

Thanks & all the best,
George

**Comment by Tiflo62** [comment]
Hello,

I have the same issue... 
Version of this add-on (0.33) 
Version of RenderDoc (1.9)
Version of Blender (2.83, 2.89, 2.90)

My RDC file contains 3D data, I checked with the textures viewer but I can import it in Blender :/

Flo

**Comment by Tiflo62** [comment]
Test this morning... It worked!  
Version of this add-on (0.32)
Version of RenderDoc (1.9)
Version of Blender (2.83) 

Amazing!

**Comment by GeorgeD80** [comment]
Hi Tiflo62,

superb! 
It worked!
Thanks so much!
