### ISSUE TITLE
ImportError: DLL load failed (renderdoc.pyd)

### ISSUE THREAD

**Issue by jokumo** [eliemichel/MapsModelsImporter#108]
- rdc-file: I downloaded a sample as described [here](https://blenderartists.org/t/google-maps-models-importer/1153561/23)
- GPU: GeForce GTX 960
- Addon: 0.3.3
- RenderDoc: tried it first with 1.9 and then 1.10
- Blender: 2.90.1 (Python 3.7.7) and then 2.83 (Python 3.7.4)

Somehow the addon is not working on my computer.
I turned on Debug Info and got the following output in the console:
`google_maps_rd failed and returned:`
` Traceback (most recent call last):`
`   File "C:\Users\joku\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 27, in <module>`
`     import renderdoc as rd`
` ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.`

I then added the following lines to _google_maps_rd.py_ to test if the path to the files (_renderdoc.pyd_ and _renderdoc.dll_) does exist, and it does. 
` try:`
`     import renderdoc as rd`
` except:`
`     print("Error: Could not load renderdoc library.")`
`     print("Python version: "+sys.version)`
`     print("sys.path contains the following paths:\n")`
`     print(*sys.path, sep = "\n")`

Now I'm not sure what happens. I imagine for everyone else it's working out of the box. I read something about compiling renderdoc against the used python version, but I can't imagine that this is the problem. Otherwise all of us would have this issue, right?

What else could I try? Any Ideas?

**Comment by jokumo** [comment]
I'm not familiar with dependency walker but it seems to me like a bunch of unresolved dependencies. And what about the "Error: Modules with different CPU types were found."?
But at least the python version should be fine.
![image](https://user-images.githubusercontent.com/16837904/98514813-5998dc80-226a-11eb-9979-8341df827c4d.png)
[renderdoc.dwi.zip](https://github.com/eliemichel/MapsModelsImporter/files/5508896/renderdoc.dwi.zip)

**Comment by maxhacker11** [comment]
Hey! I am having the exact same issue, have you made any progress? I am going crazy all day today xD

I read the same stuff about compiling against the python version too.

I also read that Blender uses Python 3.7.x and 3.8.x or something while the renderdoc can only be run with python 3.6.x.

Any sort of help would be appreciated:D I will look into the dependency walker now too.

My setup:
- GPU: NVIDIA GeForce GTX 1060 6GB
- Addon: 0.3.3
- RenderDoc: 1.5 and 1.8
- Blender: 2.90.1 and 2.82.7

**Comment by maxhacker11** [comment]
I am so pumped! I made it work!
I just switched to an older version of the AddOn, I am usin 0.3.1 now and somehow it's working!
I was encountering some new errors today initially, where I couldn't install Blender AddOn via the AddOns tab, so I had to do it manually. Not sure what fixed the problem, but it's working!! xD

**Comment by eliemichel** [comment]
Hi @maxhacker11 and @jokumo 
Version 0.3.3 was an update to support RenderDoc 1.10 (whose ABI breaks backward compatibility), if you are using an older version of RenderDoc you must indeed downgrade this add-on. I had unintentionally left that RD 1.5 or above could work even for the last release, it is now fixed thanks.

**Comment by jokumo** [comment]
@maxhacker11 Wow! Thanks for your answer. It does work now with Maps Model Importer V0.3.1 and Blender 2.83

@eliemichel What an awesome Tool you gave us here... the structure of the imported landscapes are way more accurate than what I get with GIS.
But back to the Issue. I might miss something, but I have the feeling that there's something more about this error. 
To start experimenting I made a capture with RD1.9 and one with RD1.10 to experiment with:
[bridge (RD1.9).rdc](https://drive.google.com/file/d/1kCOloprpufwwHUmFCKZv23maQkz7a9PI/view?usp=sharing)
[bridge (RD1.10).rdc](https://drive.google.com/file/d/1pgA1AQizU9fMLbTzuJbq7G_GHljK1T5D/view?usp=sharing)
(btw, I think various sample files would be a cool thing to have for new users. This way one can check if the combination of AddOn version and Blender version works even before installing (the correct version of) RenderDoc.)

I assumed that _renderdoc.pyd_ and _renderdoc.dll_ under the _.../addons/MapsModelsImporter/bin_ directory are comming with the AddOn itself and that they are independent of the currently installed version of RenderDoc or previously installed (and removed) versions of the AddOn.
So, here are my findings so far (all on a Win64-System):

### **Works for me**:
Blender 2.83.8 & AddOn 0.3.0 RC1 & bridge (RD1.9).rdc
Blender 2.83.8 & AddOn 0.3.1 & bridge (RD1.9).rdc
Blender 2.83.8 & AddOn 0.3.2 & bridge (RD1.9).rdc

### Results in a "**ReplayStatus.FileIncompatibleVersion**"-Error. 
Some people might search for it as "AttributeError: 'NoneType' object has no attribute 'GetDrawcalls' ". Guess this one is obvious: Wrong version of RenderDoc used to create the capture file:
Blender 2.83.8 & AddOn 0.3.0 RC1 & bridge (RD1.10).rdc
Blender 2.83.8 & AddOn 0.3.1 & bridge (RD1.10).rdc
Blender 2.83.8 & AddOn 0.3.2 & bridge (RD1.10).rdc

### Results in a "**ImportError: DLL load failed**: [...]" for "import renderdoc as rd" (topic of this issue):
Blender 2.83.8 & AddOn 0.3.3 & bridge (RD1.9).rdc
Blender 2.83.8 & AddOn 0.3.3 & bridge (RD1.10).rdc
Blender 2.90.1 & AddOn 0.3.0 RC1 & bridge (RD1.9).rdc
Blender 2.90.1 & AddOn 0.3.0 RC1 & bridge (RD1.10).rdc
Blender 2.90.1 & AddOn 0.3.1 & bridge (RD1.9).rdc
Blender 2.90.1 & AddOn 0.3.1 & bridge (RD1.10).rdc
Blender 2.90.1 & AddOn 0.3.2 & bridge (RD1.9).rdc
Blender 2.90.1 & AddOn 0.3.2 & bridge (RD1.10).rdc
Blender 2.90.1 & AddOn 0.3.3 & bridge (RD1.9).rdc
Blender 2.90.1 & AddOn 0.3.3 & bridge (RD1.10).rdc

Well, so far my findings. I don't have a solution yet but I will try to dedicate some time to help fixing this. (or at least to add some specific error messages (if you like me to of course :) )

I also tried it on linux and compiled a version of RenderDoc. But there I run into the hardcoded path, which (as commented in the source code) did not work. I already have an idea how to make this detail work on linux. But after hardcoding the right path of my machine there was another error which I don't remember right now.

However, as mentioned it does work with older versions and I am verry happy about such a great tool. This takes my landscape restoration plannings to another level.

**Comment by eliemichel** [comment]
> (btw, I think various sample files would be a cool thing to have for new users. This way one can check if the combination of AddOn version and Blender version works even before installing (the correct version of) RenderDoc.)

Good Idea, here you are: https://github.com/eliemichel/MapsModelsImporter-samples

> I assumed that renderdoc.pyd and renderdoc.dll under the .../addons/MapsModelsImporter/bin directory are comming with the AddOn itself and that they are independent of the currently installed version of RenderDoc or previously installed (and removed) versions of the AddOn.

Correct

Ok thanks a lot for this hard work! SO none of the versions intended for RenderDoc 1.10 work for you? The same DLLs were used for all previous version and as for 1.10 I had to rebuild them, maybe something got wrong at this moment.

**Comment by jokumo** [comment]
@eliemichel I might have found the source of this issue. I installed Python 3.9 on my Windows-PC to work on this issue and all of a sudden everything worked as expected. I just uninstalled Python to verify it, and on my computer having Python installed and added to the environment variables definitely solves the problem.
This explains also why it works on some computers and on others it won't.

### I can reproduce this on my computer with the following setup and steps:
Blender 2.90.1
MapsModelsImporter 0.3.3
RDC File version: 1.9 and 1.10 work both the same

Steps: 
- close Blender
- launch python 3.9 installer 
  - click on "modify" -> "Next"
  - check or uncheck "Add Python to environment variables"
    - if activated it will import the RDC file correctly
    - if inactive it will fail to import the RDC file
- open Blender again and import the RDC-File

I hope this helps to avoid this issue in the next version. Not sure if it's still needed, but I added some additional error handling/messages to the code in order to avoid getting confused with the "wrong RDC"-message when the problem is about importing the RenderDoc Module. I will push it to your repository later today.

**Comment by jokumo** [comment]
@eliemichel since this Issue wasn't about the RenderDoc Version to use with 0.3.3, shouldn't it stay open until it is fixed?

**Comment by eliemichel** [comment]
Let's reopen until we figure out clearly what's going on. Cause I'm not sure I understand: I don't have Python 3.9 myself, and so I am pretty sure that I've build renderdoc.pyd for python 3.8 (the one used in Blender).

**Comment by jokumo** [comment]
My guess is:
- Python 3.9 is compatible with whatever version you used to compile it. So it would not be about the Python version.
- Something got messed up with a path variable in the building process. Maybe the path is absolute now instead of relative. Maybe the DLL or PYD can't find python, unless it's provided by the windows environment variables.
- You might be able to reproduce the error by inactivate the "Add Python to environment variables" in the Python installer (whatever version you have). If you can't reproduce it, well, then my guess is probably wrong.

**Comment by eliemichel** [comment]
Ok I tried wiping out the PATH variable before starting Blender but it is still working.
Looking at the pyd using [Dependencies](https://github.com/lucasg/Dependencies) shows that the path to python37.dll is relative:

![image](https://user-images.githubusercontent.com/5802849/101246060-233b6980-3711-11eb-8d63-0605db3c1b9f.png)

Renderdoc is imported from python.exe located right next to python37.dll in the directories so it should find it anyways just in case I tried adding this directory to the PATH automatically: https://github.com/eliemichel/MapsModelsImporter/commit/b188138c5efc216de9dd498ca7d82543f926a857#diff-19beca2443bf8b2d86fd2cfc21c1c89d82b6f64139db7f9e0858d1e4cd40c458R75

So maybe you can try this: https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.5-rc1

**Comment by jokumo** [comment]
Wow, cool Tool (Dependencies). Thanks!

> So maybe you can try this: https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.5-rc1

I just tried and it does not work.

But I think I found a hint on what is different. Seems to be something about "VCRUNTIME140_1.dll". Version 0.3.2 does not search for this file but starting with 0.3.3 (or RenderDoc 1.10) it somehow requieres it. And the difference between our computers seems to be that you have this file in the system32-folder and I don't. 
![dependencies - v0 3 2 no python in path](https://user-images.githubusercontent.com/16837904/101247250-bcba4980-3718-11eb-92cf-518e96b6d2b0.png)
***
![dependencies - v0 3 3 no python in path](https://user-images.githubusercontent.com/16837904/101247331-600b5e80-3719-11eb-8cdb-379595737346.png)
***
![dependencies - v0 3 5-rc1 with python in path](https://user-images.githubusercontent.com/16837904/101247093-83350e80-3717-11eb-9aa4-935fcd26d8a8.png)

**Comment by eliemichel** [comment]
Nice catch! This would explain a lot the apparently random discrepancies among users. This DLL is part of [Visual C++ Redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) that people may or may not have installed already due to other programs requiring it. For instance on my machine it is installed globally in system32 so even w/o Python in the PATH it gets found.

I've added it to the bin directory, try RC2 hopefully we've solved this! https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.5-rc1

The reason why it started to break with 0.3.3 would be that I've used a newer version of visual studio, the previous one was using VCRUNTIME140.dll instead, which is much more widely installed.

**Comment by jokumo** [comment]
I just tried it and confirm that this issue is fixed. It works now on my computer without python in the environment variables.

**Comment by Xprogrammer777** [comment]
> Nice catch! This would explain a lot the apparently random discrepancies among users. This DLL is part of [Visual C++ Redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) that people may or may not have installed already due to other programs requiring it. For instance on my machine it is installed globally in system32 so even w/o Python in the PATH it gets found.
> 
> I've added it to the bin directory, try RC2 hopefully we've solved this! https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.5-rc1
> 
> The reason why it started to break with 0.3.3 would be that I've used a newer version of visual studio, the previous one was using VCRUNTIME140.dll instead, which is much more widely installed.

Still not working
