### ISSUE TITLE
Trying to make this run on a Mac, thru a Parallels Desktop virtual machine.

### ISSUE THREAD

**Issue by jonathankemp80** [eliemichel/MapsModelsImporter#110]
Hey there.

So... I am a mac user, but fell in love with the idea of being able to capture Google Maps 3D models...  So here I am, trying to make it work on a virtual machine.  It's not fully working yet, but I've been able to do a few things... Would like to hear from you about a few issues though.

I did manage to get so captures with older versions of Chrome and RenderDoc.  here's one : https://cp.sync.com/dl/5578fa7f0/w8v8xjfp-qsmcefud-39zdbryp-nw9j7yks

I am not able to import any of those in Blender tho.  Always get the "Invalid RDC..." error msg.

At first, I thought the captures were the problem, since RenderDoc throws a "warning" when capturing... (Something like "Couldn't create FEATURE_LEVEL_11_0 device ... "

But then, I stumbled on your sample rdc file (capture.rdc) and gave it a try.  Same problem arise with your capture... So I'm now thinking my captures might be ok, and the problem would only be related to the Blender addon... 

Tried opening the capture.rdc file in RenderDoc and got this in the Diagnostic Log : 
https://cp.sync.com/dl/ec52609c0/6wgtr8zi-xjpx2qcj-8ptzuzfm-meaazn3h

Any thoughts ?

Can at least anyone try to import my capture (eglise.rdc, from the first link above) in blender to confirm if the capture itself is ok or not ?

Many thank !

**Comment by eliemichel** [comment]
Browsing into the draw events reveals that your capture does not contain 3D information. A valid capture would have the 3D chunks appear progressively and many `DrawIndexed(n)` events with `n` varying ardoun thousands or at least hundreds. Don't forget to use the Capture after Delay feature to be sure to be moving in the viewport at the time of capture, and maybe try capturing a burst of like 4 frames in a row if it is still not working, one of them should draw 3D.
![image](https://user-images.githubusercontent.com/5802849/99875044-cb6b1180-2bec-11eb-9788-8be46ce9f2f0.png)

**Comment by jonathankemp80** [comment]
That's good to know.  Thanks for the info... I'll give it a try.

But what about the fact that I can't open your "sample" rdc file ?  Shouldn't this one be ok, and open just fine in Blender ?

**Comment by jonathankemp80** [comment]
Hey there,  just a little follow up for anyone else trying to do the same.  Got it to work with the following setup : 

MacOs High Sierra
NVidia GTX 980 Ti 6Gb

Parallels Desktop 16, running a Windows 10 VM
RenderDoc 1.6
Chrome 48.0.2564.109 (Official Build) (64-bit)
Blender 2.82
Blender Maps Model Importer addon 0.2.1

Now... I realize there is a newer version of the addon... Since I had trouble at first, I tried many versions... This is the one that was running when I first got it to work.

@Elie : Would a newer version of the addon give better results ?

**Comment by eliemichel** [comment]
Newer versions are mostly related to following the evolution of Chrome and RenderDoc, so if you're using outdated versions of these it is consistent to use an outdated version of this add-on as well. ;)
