### ISSUE TITLE
Blender is not reading the RDC file?

### ISSUE THREAD

**Issue by KeyTrent** [eliemichel/MapsModelsImporter#114]
So I had this workflow going on my old computer and was loving it, since upgrading something has changed causing it not to work. 

AMD3600x and GTX1060 currently.  

Blender says:

Invalid RDC capture file. Please make sure that:
1. You are importing from Google Maps or Google Earth web
2. You were MOVING in the 3D view while taking the capture (you can use the Capture after delay button in RenderDoc).
Please report to MapsModelsImporter developers providing the .rdc file as well as the full console log.
Console log is accessible in Windows > Toggle System Console (right click to copy).

Here are a couple .RDCs
https://drive.google.com/drive/folders/16c3p0hfwu4NHM0mYzyHSl563QFwtKWL6?usp=sharing

I open this shortcut: 

"C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog""

Inject renderdoc and capture, exactly as I did on my old computer but to no avil this time. 

One problem I had this time I didn't before was renderdoc thumbnails being black, now I've solved that by making sure all chrome instances are gone on beginning the workflow, I don't know what next to try. Thanks for any answering.

**Comment by Attreyu** [comment]
I believe that this is due to the latest RenderDoc version. 

With 1.10 it works, with 1.11 it gives those errors.

**Comment by KeyTrent** [comment]
Solved, Thank you.
