### ISSUE TITLE
Invalid RDC capture file

### ISSUE THREAD

**Issue by RutgerRauws** [eliemichel/MapsModelsImporter#116]
Hi!

I finally managed to get a hold on a Windows laptop to try this amazing Blender plugin. Unfortunately, I am unable to import the generated .RDC file. These are the versions of the software I used:

Maps Models Importer 0.3.3
Blender 2.83.9
RenderDoc 1.10
Google Chrome 87.0.4280.66

So according to the release information for 0.3.3 this should work. Unfortunately, I get the following error when importing the RDC in Blender:

> Invalid RDC capture file. Please make sure that:
> 1. You are importing from Google Maps or Google Earth web
> 2. You were MOVING in the 3D view while taking the capture (you can use the Capture after delay button in RenderDoc).
> Please report to MapsModelsImporter developers providing the .rdc file as well as the full console log.
> Console log is accessible in Windows > Toggle System Console (right click to copy).

The console log is not providing me with any useful information:
> Read prefs: C:\Users\s166825\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
> found bundled python: C:\Program Files\Blender Foundation\Blender 2.83\2.83\python
> Info: Deleted 3 object(s)

The RDC file appears to have been generated correctly. For completeness, I have uploaded the RDC file: https://we.tl/t-HchtM6R3gc I assume this does not leak any sensitive data?

I hope someone can give me a hand. Thanks in advance!

Kind regards,
Rutger

**Comment by RutgerRauws** [comment]
I realized I needed to enable the debug output from the addon settings, here are some extra details:

```
google_maps_rd failed and returned:
Traceback (most recent call last):
  File "<snip>\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 27, in <module>
    import renderdoc as rd
ImportError: DLL load failed: The specified module could not be found.
```
So it appears to be a version mismatch..

**Comment by RutgerRauws** [comment]
I finally managed to get this to work using:

Maps Models Importer 0.3.2
Blender 2.83.9
RenderDoc 1.09
Google Chrome 87.0.4280.66

**Comment by RutgerRauws** [comment]
@eliemichel Is it an idea to provide more specific software versions that work well together? So instead of only giving ranges of what 'should' work, also to provide the software version combinations that are guaranteed to work?

**Comment by eliemichel** [comment]
Yes indeed it is quite misleading because it is evolving fast (especially RenderDoc dev is very active and started to break things with versions 1.10 and 1.11 while it used to be more backward compatible). We've just added clearer instructions about this in the error message, and here as well: https://github.com/eliemichel/MapsModelsImporter-samples/

What has been guaranteed to work is what is said to be lastly tested in the Requirements section of the [release pages](https://github.com/eliemichel/MapsModelsImporter/releases) for each individual release.
