### ISSUE TITLE
MapsModelImporter 0.3.3 can't open RDC-Files from RenderDoc 1.11

### ISSUE THREAD

**Issue by jokumo** [eliemichel/MapsModelsImporter#117]
RDC-File: [alhambra-RD_1.11.rdc](https://github.com/jokumo/MapsModelsImporter-samples/blob/master/samples/alhambra-RD_1.11.rdc)
RenderDoc Version: 1.11
Capture Source: Google Maps
MapsModelImporter: 0.3.3
Blender: 2.90.1

I made the same capture with RenderDoc 1.10 and it works. But it does not work with RenderDoc 1.11.
Not sure if it's a general problem or if it's again just my computer.

Could someone confirm this Issue?

**Comment by eliemichel** [comment]
Confirmed, haven't tried 1.11 yet, seems that they changed the ABI again.

**Comment by BryanCrotaz** [comment]
1.12 doesn't work either.

Note, error message says to use version >=1.10 - can you change that to =1.10 for now?

**Comment by jokumo** [comment]
I changed the error message and made a pull request. I also changed the description in the sample file collection.
Thanks for the hint.
