### ISSUE TITLE
Having trouble importing .rdc file to Blender

### ISSUE THREAD

**Issue by SeenaM9** [eliemichel/MapsModelsImporter#118]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file - tokyotowerpass7.rdc
 - Your GPU name - Google Chrome gpu
 - Version of this add-on (must be the most recent one) - 0.3.3
 - Version of RenderDoc (1.10 recommended) - I've tried v1.09, v1.10, and v1.11.  The .rdc file was created with v1.10
 - Version of Blender (2.82 minimum) - 2.82

[RDC Screenshots.docx](https://github.com/eliemichel/MapsModelsImporter/files/5646594/RDC.Screenshots.docx)

**Comment by eliemichel** [comment]
Please upload the RDC file, its name itself wont help ^^
And I don't have Word, please share images directly here in the post.
Maybe try v0.3.4 of the add-on even though changes were for newer version of Blender.

**Comment by SeenaM9** [comment]
![renderdoc screenshot](https://user-images.githubusercontent.com/58831243/101266525-4dd2f580-3704-11eb-8cc5-183824b4e57b.jpg)
![blender screenshot](https://user-images.githubusercontent.com/58831243/101266526-4f9cb900-3704-11eb-9f95-cc32e00688c6.png)

I've invited you as a collaborator to view the tokyotowerpass7.rdc file.  Thanks for your help.  In the meantime, I'll try v0.3.4

**Comment by eliemichel** [comment]
A collaborator where?
You should actually have a look at v0.3.5 that has just been released and fixes a DLL issue. Also, you can try to import samples captures from here: https://github.com/eliemichel/MapsModelsImporter-samples/

**Comment by SeenaM9** [comment]
I used the v0.3.5 and it looks like the issue is resolved.  Thank you very much.  This is a great tool.

**Comment by eliemichel** [comment]
Great!
