### ISSUE TITLE
Cannot inject into process

### ISSUE THREAD

**Issue by DamianPe** [eliemichel/MapsModelsImporter#12]
Hello,

I have several issues and I'm stuck. I installed RenderDoc v1.1, I have Chrome 76.0.3809.132, both 64-bit running on Win10. I followed your guide and here is what i found.
1. Starting chrome with flag --use-angle=gl prevents from viewing Google Maps in 3D. They stuck in 2D mode and even if I provide copy-paste link from Edge in 3D view, it switches back to 2D. What can be a reason? Omitting this flag allows to view Google Maps in 3D;
2. My Chrome keeps killing injected process: when popup window with process id appears, I inject to it in RenderDoc. Seems OK but there is no overlay in Chrome and RenderDoc says "Connection status: Active" but "API: None" so not like in your youtube video, When I paste Google Maps address, two things happen: Chrome startd new GPU process - a new popup window with Id appears and RenderDoc shows a dialog to send a crash report to its developers. I don't know what is a cause and what is a reason. Attaching to new process Id doesn't do anything, nothing is captured.
Can you write what exact version and built of RenderDoc and Chrome are you using? And can you please clarify as it is not really clear for me: should I move around a map, pres and release PrintScr, move, press, release etc or should I keep pressing PrintScr while moving and release when I'm done?

Thanks in advance
Damian

**Comment by eliemichel** [comment]
Hi Damian,

1. I had this behavior of deactivated 3D feature with some older GPUs. Which is yours? Maybe try to add the `--ignore-gpu-blacklist` flag.

2. The chrome keeping on killing the injected process is a common issue, that I unfortunately could not reproduce. Some users reported it to work with Vivaldi, you may give it a shot. It is the same engine so the capture will play well with the Blender add-on. Regarding the capture process, you must start the move, while the mouse moves press and release PrintScr, then stop moving (the mouse). Alternatively you can ask RenderDoc to trigger the capture in a few seconds and keep moving the view until it does.

**Comment by DamianPe** [comment]
Hi,

Thanks for fast response. I tried the same config (Chrome+RenderDoc) on different machine with new GPU, still the same. Then I switched to Vivaldi browser. It is better, RenderDoc injects into GPU process, Vivaldi opens Google Maps in 3D view but still I cannot capture anything. RenderDoc shows 
![image](https://user-images.githubusercontent.com/15075524/65664235-347ee580-e039-11e9-8580-67242c4bd06b.png) - OpenGLES not presenting, which still is incorrect, I believe... What else should I try?

Regards
Damian

**Comment by gc3dvr** [comment]
hi!
i have the same problem (with chrome,chrome canary, chromium,  and vivaldi)
 browsner's message : " you used an unsupported command line indicator: --disable-gpu-sandbox"

**Comment by eliemichel** [comment]
@gc3dvr I get this warning too, it does not prevent it from working, and the flag actually does something.

@DamianPe @gc3dvr Try using Chrome 70.0, available here: https://www.slimjet.com/chrome/download-chrome.php?file=files%2F70.0.3538.77%2FChromeStandaloneSetup64.exe

Make sure 1. you uninstall Chrome first 2. You don't go to "About" menu otherwise Chrome will autoupdate 3. No chrome process is running before you start it with the appropriate flags.

**Comment by petrbahr** [comment]
I guess it simply does not support integrated GPU ? i have the same problem as @DamianPe .  The ```--ignore-gpu-blacklist ``` flag did not help, chrome/vivaldi is completly useless with that. 

I guess theres no way for us how we can use this great tool :(

**Comment by eliemichel** [comment]
Good news for people experiencing the "Not presenting" error: the very last release [v0.2.0](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.2.0-rc1) relies on a different API for injection, which should fix your issue.

Pay close attention to the new instructions, especially the new software versions and chrome.exe shortcut.

If there are still issues, open a new issue, cause they are likely to be of a different kind!
