### ISSUE TITLE
on v3.4 getting Invalid RDC capture file error

### ISSUE THREAD

**Issue by robogrow** [eliemichel/MapsModelsImporter#121]
[If](url

) you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file
 - Your GPU name - AMD Radeon 5
 - Version of this add-on (must be the most recent one)
 - Version of RenderDoc (1.10 recommended) - 1.11 not sure for Funkhaus,rdc is sample from github
![rdc_err_funkhaus](https://user-images.githubusercontent.com/8601783/101522633-80276180-3955-11eb-92a4-07eb47140db8.png)

 - Version of Blender (2.82 minimum) - 2.90

**Comment by robogrow** [comment]
oops lost rdc files and other error screenhsots
[
![clearwater_rdc](https://user-images.githubusercontent.com/8601783/101522770-b06f0000-3955-11eb-9690-3f5c52ff0511.png)
![clw_rdc](https://user-images.githubusercontent.com/8601783/101522782-b533b400-3955-11eb-9bbd-d9bf235543bb.png)
[rdc.zip](https://github.com/eliemichel/MapsModelsImporter/files/5660921/rdc.zip)


](url)

**Comment by eliemichel** [comment]
Please use the last version of the add-on (v0.3.5) and RenderDoc v1.10, not 1.11.
