### ISSUE TITLE
IDEA Improvement: Need Help to recursively import RDCs from a Folder and store each element into a Collection

### ISSUE THREAD

**Issue by fpibbs** [eliemichel/MapsModelsImporter#128]
As written in the title and kindly need @eliemichel help, my script **is almost ready** but I have some troubles because it stores only the first element on the collection under its named from file.
Hope it can help:

import bpy
import os
import sys
import glob

directory_im = 'C:/Users/fcapp/Desktop/LowPoly2/'
files = glob.glob(directory_im + "*.rdc")
for f in files:
    head, tail = os.path.split(f)
    collection_name = tail.replace('.rdc', '')
    bpy.ops.import_rdc.google_maps(filepath=(f), filter_glob="*.rdc", max_blocks=-1)
    myCol = bpy.data.collections.new(collection_name)
    bpy.context.scene.collection.children.link(myCol)
    for ob in bpy.context.selected_objects:
        myCol.objects.link(ob)

![image](https://user-images.githubusercontent.com/25976329/104120584-378a0c00-5338-11eb-86d6-6fbf2ca35bc9.png)

**Where am I wrong? Need to solve that...**

Current Configuration: 
Blender 2.91, **Maps Model Importer 0.3.5**, RenderDOC 1.10, Chrome X64 on Windows Pro  87.0.4280.141( 64 bit)

**Comment by fpibbs** [comment]
Solved by RainerTrummer - https://devtalk.blender.org/t/need-help-to-recursively-import-rdcs-from-a-folder-and-store-each-element-into-a-collection/17019/9?u=frankiepibbs(url) on Blender Forum:

[(https://devtalk.blender.org/t/need-help-to-recursively-import-rdcs-from-a-folder-and-store-each-element-into-a-collection/17019/10)]

**Comment by eliemichel** [comment]
Thanks for sharing this, I've added a link to this issue in the readme to help interested people to find it!
