### ISSUE TITLE
2 Captures with same origin  (coincidence?)

### ISSUE THREAD

**Issue by RADAC-S** [eliemichel/MapsModelsImporter#129]
Hey,
i dont know if this is an coincidence or if it can be used to optimize the super-duper-great addon.
normaly all different captures apear at a different location in blender. today i had two captures that matched perfectly after importing.
i really dont know what happened but thats the first time it happened to me. 
Maybe theres some data in those two files that can help to make it work always like this?

im not an programmer, so the only thing i can to i to share the files with you, if you want.

thank you a lot for your work, i love your addon.

cheers

**Comment by eliemichel** [comment]
It is indeed surprising, first time I hear about such a case and it never happened to me, I'd be interested in seeing these captures!

**Comment by RADAC-S** [comment]
Sorry for not responding. Now i found the time to re-check the case with an empty .blend and i can say, it still like i sayed.
#1 and #2 are matching perfectly, #3 doesnt. i also added my empty default blendfile.
WeTransfer: https://we.tl/t-5WPNqAIGNR

you said, that youre interested what people do with your addon.. i uploaded the site plan of my last architecture project, where i used the clay rendered maps-model to show the project and its surrounding in Berlin. I think i will use this method for now on always. its just a hell of work to match all the small high resultion tiles/chunks in blender into one big :)
thank you!
![LP_Sachsendamm](https://user-images.githubusercontent.com/77298794/109998601-ae78cb00-7d11-11eb-9360-3942cf4fdc2a.jpg)

**Comment by eliemichel** [comment]
Nice use case! If you're getting too tired with aligning capture you know I've developed a tool for this: https://gumroad.com/l/KSvXuu

**Comment by RADAC-S** [comment]
Wow. what a gamechanger! thank you, thats saving a lot of time :)
