### ISSUE TITLE
Add-on does not install with Blender 2.91

### ISSUE THREAD

**Issue by tiernanmartin** [eliemichel/MapsModelsImporter#130]
I could not get the add-on to show up in Blender 2.91. When I switched back to 2.8.3 it works as intended.

**Comment by eliemichel** [comment]
This is suprising, I've been using it with 2.91 for some time. Could you eventually try again and look for errors in the system console? (Window > Toggle System Console)

**Comment by tiernanmartin** [comment]
No errors in the system console. The installation process seems to work as expected but the new add-on never appears in the add-on list and Google Maps Capture doesn't appear as an option in the Import panel.

**Comment by eliemichel** [comment]
Can you find it in `C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons`? If so, and it is not listed, remove the directory from there and install again. If not, it means Blender did not install it, and in this case there must really be an error in the system console (check **after** you try to install the addon, not before, and w/o closing blender in between)

**Comment by tiernanmartin** [comment]
You're right. It was installing successfully but it was not automatically enabled. Silly mistake on my part. Thanks for your assistance @eliemichel.
