### ISSUE TITLE
I can't open the Alhambra example

### ISSUE THREAD

**Issue by josecrespoc** [eliemichel/MapsModelsImporter#131]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file:  https://github.com/eliemichel/MapsModelsImporter-samples/blob/master/samples/alhambra-RD_1.11.rdc
 - Your GPU name: NVIDIA GeForce GTX 950M
 - Version of this add-on (must be the most recent one): 0.3.5
 - Version of RenderDoc (1.10 recommended): 1.11
 - Version of Blender (2.82 minimum) 2.91

Read prefs: C:\Users\Jose\AppData\Roaming\Blender Foundation\Blender\2.91\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.91\2.91\python

==========================================================================================
google_maps_rd failed and returned:
Loading capture from C:\Users\Jose\Desktop\alhambra-RD_1.11.rdc...
Couldn't open file: ReplayStatus.FileCorrupted
Traceback (most recent call last):
  File "C:\Users\Jose\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 290, in <module>
    main(controller)
  File "C:\Users\Jose\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 282, in main
    scraper.run()
  File "C:\Users\Jose\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 207, in run
    drawcalls = controller.GetDrawcalls()
AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'

Extra info:
 - python = C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\python.EXE
 - python_home = C:\Program Files\Blender Foundation\Blender 2.91\2.91\python
Invalid RDC capture file. Please make sure that:
1. You are using the recommended RenderDoc Version for this AddOn
   - RenderDoc Version 1.5 - 1.9 for MapsModelsImporter <= 0.3.2
   - RenderDoc Version >= 1.10 for MapsModelsImporter >= 0.3.3
2. You are importing from Google Maps or Google Earth web
3. You were MOVING in the 3D view while taking the capture (you can use the "Capture after delay"-button in RenderDoc).

Before opening a new Issue on GitHub please download a working sample file to check if this works on your Computer.
Please be patient. If there's no error message it might still be loading.
It can take a minute or two to load it and Blender will get unresponsive during this time.
Find sample files here: https://github.com/eliemichel/MapsModelsImporter-samples

If it works with a sample file you most probably shouldn't open a new issue on GitHub but figure out how to use RenderDoc.
Find instructions about using RenderDoc by searching YouTube for "Capturing Google Maps with RenderDoc"

If the sample file doesn't work:
Please report to MapsModelsImporter developers providing the full console log with debug information.
First turn on debug output by activating the "Debug Info"-checkbox under Edit > Preferences > Add-ons > MapsModelsImporter
On Windows systems console log is accessible in Windows > Toggle System Console (right click to copy).
On Linux systems you have to run Blender from the console to get the debug output

==========================================================================================
google_maps_rd failed and returned:
Loading capture from C:\Users\Jose\Desktop\alhambra-RD_1.11.rdc...
Couldn't open file: ReplayStatus.FileCorrupted
Traceback (most recent call last):
  File "C:\Users\Jose\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 290, in <module>
    main(controller)
  File "C:\Users\Jose\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 282, in main
    scraper.run()
  File "C:\Users\Jose\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 207, in run
    drawcalls = controller.GetDrawcalls()
AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'

Extra info:
 - python = C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\python.EXE
 - python_home = C:\Program Files\Blender Foundation\Blender 2.91\2.91\python
Invalid RDC capture file. Please make sure that:
1. You are using the recommended RenderDoc Version for this AddOn
   - RenderDoc Version 1.5 - 1.9 for MapsModelsImporter <= 0.3.2
   - RenderDoc Version >= 1.10 for MapsModelsImporter >= 0.3.3
2. You are importing from Google Maps or Google Earth web
3. You were MOVING in the 3D view while taking the capture (you can use the "Capture after delay"-button in RenderDoc).

Before opening a new Issue on GitHub please download a working sample file to check if this works on your Computer.
Please be patient. If there's no error message it might still be loading.
It can take a minute or two to load it and Blender will get unresponsive during this time.
Find sample files here: https://github.com/eliemichel/MapsModelsImporter-samples

If it works with a sample file you most probably shouldn't open a new issue on GitHub but figure out how to use RenderDoc.
Find instructions about using RenderDoc by searching YouTube for "Capturing Google Maps with RenderDoc"

If the sample file doesn't work:
Please report to MapsModelsImporter developers providing the full console log with debug information.
First turn on debug output by activating the "Debug Info"-checkbox under Edit > Preferences > Add-ons > MapsModelsImporter
On Windows systems console log is accessible in Windows > Toggle System Console (right click to copy).
On Linux systems you have to run Blender from the console to get the debug output

**Comment by josecrespoc** [comment]
@eliemichel could you help me please? Many thanks!

**Comment by eliemichel** [comment]
Hi Jose,
I should hide this capture for now, RenderDoc v1.11 is still not supperted yet, you should downgrade to v1.10 when doing your own captures! I could not take the time to update the add-on yet, it's a bit annoying to do because I have to change some parts of RenderDoc's source code at each breaking update, I did not fully automate the process.
É.
