### ISSUE TITLE
No debug info in Chrome & RenderDoc isn't set up properly; no API

### ISSUE THREAD

**Issue by butterfliesarecute** [eliemichel/MapsModelsImporter#138]
So I'm very interested in importing 3d data from Google Maps into Blender 2.91. Having followed all the instructions in this video to a T (https://youtu.be/F_XsmoZJmG8) I'm noticing that firstly when I launch the debugged Google Chrome shortcut in my desktop, yes, I am getting the popup with the Google Chrome GPU number but unlike in the video, I don't get a dark bar at the top of my Chrome browser with the debugging information and I feel I should.

Anyway, I go into Google Maps, then launch RenderDoc v1.11. But then something strange happens, and this is where my other issue comes in. As I just said, I have Maps open in debugged Chrome. I go through the "Inject into Process" steps using the number I got in my popup when I launched Chrome. But then if you look at the screencaps, you'll see that I'm unable to click on any of the options to capture the frames from my desired location in Maps.

Additionally, I should note that the API is set to "None" and I don't know how to fix this. Secondly, when I go back to "Inject into Process" and this time search for "chrome" in the long bar next to the "Refresh" button, a list comes up with different PID numbers, one being the number I got when I launched Chrome and another being the Google Maps window tab that is active. Firstly, why are these PID numbers not the same assuming this matters? Also, why is it that when I click on either thing, I am still unable to capture the frames?

Thanks for any help anyone can offer me. Here are the screencaps:

![Screenshot (149)](https://user-images.githubusercontent.com/77900853/105614666-ae8fbd80-5d98-11eb-8ca7-a2eedddc2bc5.png)
![Screenshot (150)](https://user-images.githubusercontent.com/77900853/105614667-af285400-5d98-11eb-8800-bbd32c49e618.png)
![Screenshot (151)](https://user-images.githubusercontent.com/77900853/105614668-afc0ea80-5d98-11eb-944e-f03e723dac30.png)

**Comment by butterfliesarecute** [comment]
Anyone?

**Comment by eliemichel** [comment]
Hello @butterfliesarecute,

1. Use RenderDoc v1.10, not 1.11 (cf [release notes](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.5-rc1))
2. Inject into the process **before** clicking on the gpu popup, otherwise you won't get the overlay and in that case no need to try further, if you don't have the overlay you won't be able to capture.

**Comment by butterfliesarecute** [comment]
> Hello @butterfliesarecute,
> 
> 1. Use RenderDoc v1.10, not 1.11 (cf [release notes](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.5-rc1))
> 2. Inject into the process **before** clicking on the gpu popup, otherwise you won't get the overlay and in that case no need to try further, if you don't have the overlay you won't be able to capture.

Hello there, Elie Michel. I just wanted you to tell your I followed your advice and it worked for me. This solution fixed the issue, so thanks a lot! Cheers!

**Comment by DDVictor** [comment]
Hello, 
I've used a few times RenderDoc, then on Blender 4 it wasn't working properly to import the captures. I installed Blender 3.5, it worked but suddenly Chrome stopped showing me the code to inject into process. It just opens a normal Chrome window after a very quick screen appears and closes right away I can't even see. Any idea what could be happening? 
Thanks,
