### ISSUE TITLE
Additional Geometry on Tile Boundry

### ISSUE THREAD

**Issue by LorenzWieseke** [eliemichel/MapsModelsImporter#144]
After import the mesh has this tile pattern :
![image](https://user-images.githubusercontent.com/29607121/106923631-93b13780-670e-11eb-9617-81a50e37cfff.png)

This produces unnecessary geometry. Any idea how to get rid of that or remesh somehow. Using blenders remeshing tools will kill the uv's.

Thanks and best regards, Lorenz

**Comment by JM075** [comment]
Hello Lorenz,
This is the uderground geometry built in source data for joigning tiles.
Generally you see them if you look from below ground, not from above.
Best regards
JM

**Comment by LorenzWieseke** [comment]
And do you see any chance of getting rid of that extra geometry?  I used the decimate modifier in blender and chose planar with respekt to UV.  that got rid of you faces. I try to User select side of active function but the whole model is not on the same level so  it's not working

**Comment by eliemichel** [comment]
There is no obvious process to get rid of those at the moment.

**Comment by LorenzWieseke** [comment]
I read that you are developing a cleanup addon so I looked at all your repositories but couldn't find it. Are there any news on it ?

Also joining the mesh and merging verts seems to work pretty decent to get the vert count down.

**Comment by LorenzWieseke** [comment]
Hi Elie,

just yesturday I found your neat little blender addon to import map models from renderdoc. I then bought your addon to pack all the textures so one can use only one material. Nice tool by the way and big performance boost !

Now that I got my first models up and running online I wondered how to automate the process of getting and optimizing the model.

I wrote an addon to dynamically scale images, so reducing the tex size is already a one click solution. It also bakes lightmaps and ao for gltf but that just makes sense when you have your own model and want to include it in a google maps scene, eg for architecture.

Now I wonder how to reduce, retopoligize the mesh. UV Unwrap takes ages and thou draco does a good job on quantifying the vertex positions, still the file is pretty big to load on web / mobile.

I already wrote you about the tile issue on github but wantet to ask some more :

Do you know if the mesh in google maps is generated proceduraly or if there is an LOD for the Mesh as well (like for textures) ?

Do you think this hole render doc -> inject chrome pid thing can be put in the addon ? I think its basically a batch, start chrome, start renderdoc, open maps, wait for user input, save rdc and import.

Maybe if you got dome time I would be happy to here some second thoughts.

Best Regards, Lorenz

Am 04.02.2021 20:36 schrieb Elie Michel <notifications@github.com>:

There is no obvious process to get rid of those at the moment.

**Comment by eliemichel** [comment]
(I replied to you email in the end iirc, closing this)
