### ISSUE TITLE
Avoid chrome uninstall step

### ISSUE THREAD

**Issue by tetreum** [eliemichel/MapsModelsImporter#15]
Having to uninstall your daily browser isn't simply an option for most people so:
A portable version can be obtained from PortableApps.com http://sf.net/projects/portableapps/files/Google%20Chrome%20Portable/GoogleChromePortable_70.0.3538.110_online.paf.exe

In order to set the flags simply save this as `GoogleChromePortable.ini` in the same folder where `GoogleChromePortable.exe` is present:
```ini
[GoogleChromePortable]
Google ChromeDirectory=App\Chrome-bin
ProfileDirectory=Data\profile
SettingsDirectory=Data\settings
AdditionalParameters=--disable-gpu-sandbox --gpu-startup-dialog --use-angle=gl
Google ChromeExecutable=chrome.exe
WaitForProgram=true
DisableSplashScreen=false
RunLocally=false
CacheInTemp=true
ImportJava=false
PortablePasswords=false
```

Then just run `GoogleChromePortable.exe`

I tested it and works properly.

What settings do you recommend in renderdoc if one wants to record a way longer sample?
I don't see a way to tell it to "Capture nonstop/while key is pressed" or at least "combine multiple captures"

**Comment by eliemichel** [comment]
Thanks, I was looking for such portable version!

To capture a sequence, you can set up capture burst in RenderDoc UI, to capture every n second. Beware that there is no automatic way of adjusting the captures in the add-on. It tries to match the orientation, but the scale may change, and if you capture at a level where earth curvature matters you'll have to adjust everything manually.

**Comment by tetreum** [comment]
Again sorry for bothering you, i know it's not your problem:
Argh, so position is not saved and having multiple captures implies manual reposition of them in blender right?
Huh, every bit is so beatiful, even when it's a mix/overlapped places:
![https://i.imgur.com/EKU9jM3.png](https://i.imgur.com/EKU9jM3.png)

I can only think on capturing gmaps url on each capture to know the coords and try to use them for x,y placing in blender

**Comment by eliemichel** [comment]
Yes even though I tried I could not get a proper way of registrating multiple captures together consistently. :/

**Comment by odartgp** [comment]
Hi and thank you for such an interesting addon! I have a quick question: Once I have installed the chrome portable version, How is the process to set the flags? I mean how I create the GoogleChromePortable.ini file with this instructions:

[GoogleChromePortable]
Google ChromeDirectory=App\Chrome-bin
ProfileDirectory=Data\profile
SettingsDirectory=Data\settings
AdditionalParameters=--disable-gpu-sandbox --gpu-startup-dialog --use-angle=gl
Google ChromeExecutable=chrome.exe
WaitForProgram=true
DisableSplashScreen=false
RunLocally=false
CacheInTemp=true
ImportJava=false
PortablePasswords=fals

I am not a programmer, just a Blender user and I am kind of lost in thins step. 

Thank you in advance!

**Comment by tetreum** [comment]
Use notepad, it even if you save it as `GoogleChromePortable.ini` Windows will save it as `GoogleChromePortable.ini.txt` (because they're retards), so you then have to rename it back to `GoogleChromePortable.ini`

**Comment by odartgp** [comment]
Thank you for your fast response!. 
Will do
:) :) :)
