### ISSUE TITLE
Importing RDC from Google Earth (partially) fails

### ISSUE THREAD

**Issue by jokumo** [eliemichel/MapsModelsImporter#151]
I am attempting to import through Google Earth Web (via chrome browser).  
[...]
I am able to import various test file such as Funkhaus.rdc without issue.
[...]
**UPDATE:**  Confirmed google maps works fine.  Google Earth Web appears to be busted.
Google Earth Web RDC files do not import at all on Win 10 64bit, RenderDoc 1.10, MapsModelImporter 3.5 rc2 (latest), and Blender 2.82.

_Originally posted by @polygonfuture in https://github.com/eliemichel/MapsModelsImporter/issues/146#issuecomment-783742534_

The capture definitely contains 3D information. I see it in the list of data captured.
Would you be able to verify a working google earth capture on your end and push the  rdc to your repo of samples?

_Originally posted by @polygonfuture in https://github.com/eliemichel/MapsModelsImporter/issues/146#issuecomment-784007743_

**Comment by jokumo** [comment]
I just tried it and I can confirm that on my computer it's not working exactly as expected. I used RenderDoc 1.10 with Blender 2.92.2 and MapsModelsImporter 0.3.5_rc2.

I made 8 captures in two runs, first run with 3 captures and second run with 5 captures. 
Two of them can be imported without getting an error, but one of them has data a little bit offset to what I was looking at, the other has a very huge area around it included. The others fail during the import process rather than failing immediately. Some of them import some polygons and fail, others fail before importing anything (but they are processing data before failing). Some of them do contain parts of the whole Globe/Earth, so what I actually tried to capture is so tiny that it's really hard to locate.

My conclusion is that there are two things happening with captures of Google Earth:

- The captures from Google Earth contain way more data outside of the viewed objects. I think this is due to the way Google Earth works and there might not be a fix for it since RenderDoc just makes a snapshot of what it can find in the memory/ram. 
- The captured RDC-Files made with Google Earth contains data that breaks the import function at an unexpected point (AddOn 0.3.5). 

@polygonfuture If it works with rdc-files made with Google Maps I would suggest do it that way for the moment.
Do you see any advantages in using Google Earth instead of Google Maps? Do I miss something?

**Comment by eliemichel** [comment]
Could one of you share one of these faulty captures?

**Comment by polygonfuture** [comment]
Hi there,

Sure here is a capture that errors.  I couldnt zip it to the limited file size of 10mb so here's a google drive link:

[https://drive.google.com/drive/folders/12hBQzABnzE7n0JaR1hpIt49Ek6xEZfp0?usp=sharing](https://drive.google.com/drive/folders/12hBQzABnzE7n0JaR1hpIt49Ek6xEZfp0?usp=sharing
)

**Comment by eliemichel** [comment]
Ok I might have found a more robust way to import from Earth, check this new version: https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.6

![image](https://user-images.githubusercontent.com/5802849/112719009-c4377580-8ef6-11eb-870e-86c3e1b821f1.png)

**Comment by polygonfuture** [comment]
Thank you so much @eliemichel I'll give it a try today and report back.

**Comment by jokumo** [comment]
> 
> Ok I might have found a more robust way to import from Earth, check this new version: https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.6

@eliemichel Awesome work. I just checked it with a new installation of Blender 2.92 and Addon 0.3.6 and the RDC-Files I made last time (they did not import properly with 0.3.5). Now all of them do import properly.

There's one thing to mention maybe... all of the captures were buried under some big low resolution polygons. In order to see the high resolution polygons I had to delete the low resolution polygons first, which had several layers. This might confuse some users until they find out...

@polygonfuture How is it on your computer?

**Comment by jokumo** [comment]
@eliemichel uuh, it seems like 0.3.6 only works for google earth. At least on my computer all the sample files cause an error. Take a look [here](https://github.com/eliemichel/MapsModelsImporter/issues/156#issuecomment-809464282).

**Comment by Sulekha02** [comment]
@eliemichel I used the latest release of MapsModelsImporte - v0.3.6
Still not able to import RDC from renderDoc 
And not able to use your sample files.
Here is the console file.

[console text from blender using sample file.txt](https://github.com/eliemichel/MapsModelsImporter/files/6224176/console.text.from.blender.using.sample.file.txt)

**Comment by jokumo** [comment]
@Sulekha02 On my end v0.3.6 only works for captures from Google Earth. Unfortunately all the sample files don't work with 0.3.6 (at least on my pc)
Since you posted to the "RCD from Google Earth"-Thread I suppose you are trying to import from Google Earth, is this correct?
And did you also try with v0.3.5? (just to make sure)

**Comment by Sulekha02** [comment]
@jokumo @eliemichel 

Yes, I am trying to get google earth data. I have tried RDC file of google earth from RenderDoc v1.10  on add-on v 0.3.6. 
Where can I get earlier versions of add-on to try?

**Comment by jokumo** [comment]
@Sulekha02 To get an earlier Version you have to go to the [releases page ](https://github.com/eliemichel/MapsModelsImporter/releases)and scroll down.

Google Earth ([earth.google.com](earth.google.com/))and Google Maps ([maps.google.com](https://www.google.com/maps/@38.923066,-77.0155781,70a,35y,43.5h,63.04t/data=!3m1!1e3))are two different products of Google. They have a slightly different approach on how they use 3D-Data hence what you capture with RenderDoc gives you different content of the resulting RDC-File. This Plugin was made for Google Maps and it works really good with Google Maps, expect the newest version 0.3.6, which seems to only work with Google Earth.

**Comment by eliemichel** [comment]
Sorry all, I fixed 0.3.6 eventually but to make things clearer to everybody I just made it a new release: [v0.3.7](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.7)
