### ISSUE TITLE
Cannot import RDC

### ISSUE THREAD

**Issue by pieterbooysen** [eliemichel/MapsModelsImporter#153]
Hi there

I’m trying to use RenderDoc to import an airport model into Blender 2.91

RenderDoc v.1.12
MapsModelsImporter v.0.3.5
I did the import from Google Maps in 3D view

 

Here is the error message from the log in Blender:

Read prefs: C:\Users\Pieter\AppData\Roaming\Blender Foundation\Blender\2.91\config\userpref.blend
found bundled python: E:\Program Files\Blender Foundation\Blender 2.91\2.91\python
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Pieter\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\ext_master.py'
Writing userprefs: 'C:\Users\Pieter\AppData\Roaming\Blender Foundation\Blender\2.91\config\userpref.blend' ok

==========================================================================================
google_maps_rd failed and returned:
Loading capture from E:\Blender Projects\FAOR_Dev\faor.rdc...
Couldn't initialise replay: 15
This is likely due to an unsupported version of RenderDoc.
Traceback (most recent call last):
  File "C:\Users\Pieter\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 290, in <module>
    main(controller)
  File "C:\Users\Pieter\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 282, in main
    scraper.run()
  File "C:\Users\Pieter\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 207, in run
    drawcalls = controller.GetDrawcalls()
AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'

Extra info:
- python = E:\Program Files\Blender Foundation\Blender 2.91\2.91\python\bin\python.EXE
- python_home = E:\Program Files\Blender Foundation\Blender 2.91\2.91\python
Invalid RDC capture file. Please make sure that:
1. You are using the recommended RenderDoc Version for this AddOn
   - RenderDoc Version 1.5 - 1.9 for MapsModelsImporter <= 0.3.2
   - RenderDoc Version >= 1.10 for MapsModelsImporter >= 0.3.3
2. You are importing from Google Maps or Google Earth web
3. You were MOVING in the 3D view while taking the capture (you can use the "Capture after delay"-button in RenderDoc).

Before opening a new Issue on GitHub please download a working sample file to check if this works on your Computer.
Please be patient. If there's no error message it might still be loading.
It can take a minute or two to load it and Blender will get unresponsive during this time.
Find sample files here: https://github.com/eliemichel/MapsModelsImporter-samples

If it works with a sample file you most probably shouldn't open a new issue on GitHub but figure out how to use RenderDoc.
Find instructions about using RenderDoc by searching YouTube for "Capturing Google Maps with RenderDoc"

Sent from Mail for Windows 10

Please assist and thank you !

Regards
Peter

**Comment by eliemichel** [comment]
Hello Peter,

RenderDoc must be in version 1.10, later versions are not supported yet! I updated the error message to state that in the error message but what it was specified in the release instructions, readme and youtube video description. ;)

É.
