### ISSUE TITLE
.RDC not opening in Blender

### ISSUE THREAD

**Issue by Heretohelpwithallyourneeds** [eliemichel/MapsModelsImporter#154]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file
Can't upload the file because it is too larhe even zipped
 - Your GPU name
 AMD 10

 - Version of this add-on (must be the most recent one)
 0.3.5
 - Version of RenderDoc (1.10 recommended)
 1.11
 - Version of Blender (2.82 minimum)
2.82

**Comment by Heretohelpwithallyourneeds** [comment]
Also not that the 1.11 specific .rdc sample did not work either

**Comment by eliemichel** [comment]
Do not use 1.11, use 1.10!

**Comment by Heretohelpwithallyourneeds** [comment]
Sorry about that :)
