### ISSUE TITLE
RDC files which previously imported into Blender no longer do - SOLVED

### ISSUE THREAD

**Issue by lambchop123** [eliemichel/MapsModelsImporter#156]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file
 - Your GPU name - Nvidia M5000
 - Version of this add-on (must be the most recent one) - yes
 - Version of RenderDoc (1.10 mandatory) - 1.10
 - Version of Blender (2.82 minimum)  2.82 & 2.92

-------------------------------------------------------------------------

Older RDC files that previously imported fine into Blender 2.8 now no longer import into Blender - not 2.82 or 2.92 (latest).
Also tried updating the MapsModelsImporter to latest 3.6 version on both Blender versions.

Renderdoc 1.10
Blender 2.82 and 2.92
MapsModels importer 0.3.6 and previous version.

To repeat, this was working fine, so all the RDC files are correct. Now, no RDC files will import into either versions of Blender and either versions of add-on - and I have the error 'Invalid RDC capture file'.

GPU Nvidia M5000 - no new drivers were installed for >1 month.

**Comment by lambchop123** [comment]
Download link to RDC that previously worked. 

https://we.tl/t-JbYgOLVncv

**Comment by jokumo** [comment]
@lambchop123 thanks for the feedback. Version 0.3.6 got published just two days ago. On my pc your rdc does not work with this version. And I just realize that none of the sample files from the [sample files repo ](https://github.com/eliemichel/MapsModelsImporter-samples)do work with the newest version.

However, I can't confirm that the previous versions do not work anymore. Here is how it behaves on my pc:
This worked:
Blender 2.83.8 & AddOn 0.3.3
Blender 2.83.8 & AddOn 0.3.5_rc2
Blender 2.92.0 & AddOn 0.3.5_rc2

This did not work:
Blender 2.83.8 & AddOn 0.3.2
Blender 2.83.8 & AddOn 0.3.6
Blender 2.92.0 & AddOn 0.3.6

Could you try again with Version 0.3.5 and confirm that this really does not work on your pc?

**Comment by sk9288go** [comment]
Similar problems with my computer here as well, For me I tried with **Blender 2.92 & AddOn 0.3.6 / AddOn 0.3.3** and both didn't work so i downgraded to **Blender2.82 & AddOn 0.3.3** and it started to work with the rdc files that are made from lower version than 1.10.

**Comment by Naimas** [comment]
probably a compatibility issue with the latest blender version?

**Comment by lambchop123** [comment]
I've got this working now. I'm using Renderdoc 1.9 and addon 0.3.5. This works with old and new RDCs created.

**Comment by lambchop123** [comment]
with Blender 2.92.

**Comment by eliemichel** [comment]
Sorry v0.3.6 was indeed buggy I released too fast there should have been a RC, so it's been updated and to make things clear there is now a [v0.3.7](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.7) with the fix.
