### ISSUE TITLE
Can't Import RDC file in blender

### ISSUE THREAD

**Issue by Naimas** [eliemichel/MapsModelsImporter#160]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file 
 - Your GPU name Nvidia 9800Ti
 - Version of this add-on (0.3.6)
 - Version of RenderDoc (1.13)
 - Version of Blender (2.91.2)

**Comment by Naimas** [comment]
Cant import file in blender as it always says error Rdc file .

**Comment by pl4sma2389** [comment]
Getting this too with the latest version, trying to import one of the test files (the mine one). Works fine with 0.3.5, but in .6 it throws this error:
`==========================================================================================
google_maps_rd failed and returned:
Loading capture from C:\Users\Aaron Smith\Downloads\Mine.rdc...
Trying scraping strategy #4...
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 1.000000)
(Skipping drawcall ClearDepthStencilView(D=1.000000, S=00))
(Skipping drawcall Draw(4))
(Skipping drawcall Draw(4))
Not relevant yet: ClearRenderTargetView(0.000000, 0.000000, 0.000000, 1.000000)
Not relevant yet: ClearDepthStencilView(D=1.000000, S=00)
Not relevant yet: DrawIndexed(2556)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: ClearDepthStencilView(S=00)
Not relevant yet: DrawIndexed(86)
Not relevant yet: ClearDepthStencilView(D=1.000000, S=00)
Not relevant yet: Draw(6)
Not relevant yet: Draw(24)
Not relevant yet: Draw(12)
Not relevant yet: Draw(42)
Not relevant yet: Draw(12)
Not relevant yet: Draw(12)
Not relevant yet: Draw(42)
Not relevant yet: Draw(30)
Not relevant yet: Draw(18)
Not relevant yet: Draw(60)
Not relevant yet: Draw(42)
Not relevant yet: Draw(12)
Not relevant yet: Draw(12)
Not relevant yet: Draw(6)
Not relevant yet: Draw(48)
Not relevant yet: Draw(42)
Not relevant yet: Draw(60)
Not relevant yet: Draw(30)
Not relevant yet: Draw(6)
Not relevant yet: Draw(12)
Not relevant yet: Draw(42)
Not relevant yet: Draw(24)
Not relevant yet: Draw(24)
Not relevant yet: Draw(48)
Not relevant yet: Draw(12)
Not relevant yet: Draw(6)
Not relevant yet: Draw(42)
Not relevant yet: Draw(18)
Not relevant yet: Draw(6)
Not relevant yet: Draw(12)
Not relevant yet: Draw(6)
Not relevant yet: Draw(18)
Not relevant yet: Draw(6)
Not relevant yet: Draw(6)
Not relevant yet: Draw(18)
Not relevant yet: Draw(18)
Not relevant yet: Draw(6)
Not relevant yet: Draw(36)
Not relevant yet: Draw(24)
Not relevant yet: Draw(6)
Not relevant yet: Draw(6)
Not relevant yet: Draw(6)
Not relevant yet: Draw(30)
Not relevant yet: Draw(18)
Not relevant yet: Draw(24)
Not relevant yet: Draw(12)
Not relevant yet: Draw(6)
Not relevant yet: Draw(6)
Not relevant yet: Draw(24)
Not relevant yet: Draw(12)
Not relevant yet: Draw(12)
Not relevant yet: Draw(24)
Not relevant yet: Draw(6)
Not relevant yet: Draw(6)
Not relevant yet: Draw(24)
Not relevant yet: Draw(12)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Draw(4)
Not relevant yet: Present(ResourceId::125)
Traceback (most recent call last):
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 299, in <module>
    main(controller)
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 291, in main
    scraper.run()
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 217, in run
    relevant_drawcalls, capture_type = self.extractRelevantCalls(drawcalls)
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 198, in extractRelevantCalls
    return self.extractRelevantCalls(drawcalls, _strategy=_strategy+1)
  File "C:\Users\Aaron Smith\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 166, in extractRelevantCalls
    if self.hasUniform(skipped_drawcalls[0], "_uMeshToWorldMatrix"):
IndexError: list index out of range


Extra info:
 - python = S:\Alt Program Files\Blender Foundation\Blender 2.92\2.92\python\bin\python.EXE
 - python_home = S:\Alt Program Files\Blender Foundation\Blender 2.92\2.92\python
Invalid RDC capture file. Please make sure that:
1. You are using the recommended RenderDoc Version for this AddOn
   - RenderDoc Version 1.5 - 1.9 for MapsModelsImporter <= 0.3.2
   - RenderDoc Version >= 1.10 for MapsModelsImporter >= 0.3.3
2. You are importing from Google Maps or Google Earth web
3. You were MOVING in the 3D view while taking the capture (you can use the "Capture after delay"-button in RenderDoc).

Before opening a new Issue on GitHub please download a working sample file to check if this works on your Computer.
Please be patient. If there's no error message it might still be loading.
It can take a minute or two to load it and Blender will get unresponsive during this time.
Find sample files here: https://github.com/eliemichel/MapsModelsImporter-samples

If it works with a sample file you most probably shouldn't open a new issue on GitHub but figure out how to use RenderDoc.
Find instructions about using RenderDoc by searching YouTube for "Capturing Google Maps with RenderDoc"

If the sample file doesn't work:
Please report to MapsModelsImporter developers providing the full console log with debug information.
First turn on debug output by activating the "Debug Info"-checkbox under Edit > Preferences > Add-ons > MapsModelsImporter
On Windows systems console log is accessible in Windows > Toggle System Console (right click to copy).
On Linux systems you have to run Blender from the console to get the debug output
reloading addon: MapsModelsImporter 1617385010.210193 1617385143.3121924 'C:\\Users\\Aaron Smith\\AppData\\Roaming\\Blender Foundation\\Blender\\2.92\\scripts\\addons\\MapsModelsImporter\\__init__.py'
Modules Installed () from 'C:\\Users\\Aaron Smith\\Downloads\\MapsModelsImporter-v0.3.5-rc2.zip' into 'C:\\Users\\Aaron Smith\\AppData\\Roaming\\Blender Foundation\\Blender\\2.92\\scripts\\addons'`

**Comment by Naimas** [comment]
I tried the newest release the b version but its still not working , error Importing RDC file .

**Comment by Naimas** [comment]
I did a test, the version 0.3.6b works with version 1.10 of RenderDoc , but not with the latest Version 1.13.

**Comment by eliemichel** [comment]
Yes it is not intended to work with 1.13 anyways!
