### ISSUE TITLE
Cannot open 3D mode in neither the chrome provided, Vivaldi nor google Chrome with --use-angle=gl

### ISSUE THREAD

**Issue by Chaos02** [eliemichel/MapsModelsImporter#17]
Have tried already everything I read in the other issue and neither Vivaldi nor any chrome version (normally using chrome canary) but RenderDoc 1.2 can hook into vivaldi and is reporting OpenGLES on my Macbook Pro 2012 with Bootcamp...?

As said already tried everything but even when I hook into vivaldi without the flag Maps wont open 3D mode and says its unavailable

I would really like to use the 3D scans as a basis for some modelling of a mountain scene and practicing shading skills

**Comment by Chaos02** [comment]
turns out that it also doesnt work on my actual desktop with an rx480...
Google wont let me 3D-View with that argument... :/

**Comment by eliemichel** [comment]
Have you tried with this very version of chrome? https://www.slimjet.com/chrome/download-chrome.php?file=files/70.0.3538.77/ChromeStandaloneSetup64.exe
I've had only little feedback on ATI GPUs, it might be the problem, though I cannot be sure.

**Comment by Chaos02** [comment]
> Have you tried with this very version of chrome? https://www.slimjet.com/chrome/download-chrome.php?file=files/70.0.3538.77/ChromeStandaloneSetup64.exe
> I've had only little feedback on ATI GPUs, it might be the problem, though I cannot be sure.

Surprisingly this worked!
Injection is not working rn but will fiddle around with it

**Comment by Chaos02** [comment]
Is now working!
Thank you very much!! :)
