### ISSUE TITLE
The add-on doesn't work with the newest version of blender (2.93)

### ISSUE THREAD

**Issue by TheFip** [eliemichel/MapsModelsImporter#172]
If i use the previous version of Blender to open the .rdc file it opens just fine, but when i tried to open it with the new update it kept giving an error.

**Comment by eliemichel** [comment]
Confirmed, there is a change of underlying version of Python with the 2.93, I'll have to rebuild the C++ part of the add-on.

**Comment by mupfelofen-de** [comment]
Since I installed Blender using the Windows Store, I can't simply downgrade to an earlier version. I hope this issue will fix soon. Can't wait to give it a try. :-)

**Comment by eliemichel** [comment]
Fixed with v0.4.0
