### ISSUE TITLE
overlaying multiple captures - or forcing high LOD

### ISSUE THREAD

**Issue by netpipe** [eliemichel/MapsModelsImporter#173]
it might need to use GPS coords better so we can overlay multiple captures when importing into blender. a way to force max level of detail in the models would be awesome for high resolution shots or easy high res building captures with sign textures and cars on buildings that are 1km+ in size. also would make getting city shots easier.

**Comment by Heath123** [comment]
If you want to force high resolution but don't want to manually stich together segments you could try using the tools at https://github.com/retroplasma/earth-reverse-engineering to request the data directly from the servers?

**Comment by eliemichel** [comment]
Hi, besides Heath123's link, you can also use Ctrl+Mouse Wheel to trick google maps into thinking you have a very wide screen and hence have it load higher resolution meshes, and to merge/stitch several captures you can use this extra add-on: [LilyCaptureMerger](https://eliemichel.gumroad.com/l/KSvXuu).

Unfortunately there is no way to extract proper GPS coords from a capture file, I wish we could indeed!
