### ISSUE TITLE
Hi Elie. Can't install LilyTexturePacker in latest Blender 2.93

### ISSUE THREAD

**Issue by ruifortes** [eliemichel/MapsModelsImporter#175]
I'm using LilyTexturePacker-v1.1.3-64bit.zip and here's the error:
![UdOLBNZb0Z](https://user-images.githubusercontent.com/4864714/123279723-08d7aa80-d500-11eb-9da2-944a5b85265b.jpg)

I just installed the OS so I might be missing some prerequisite

**Comment by eliemichel** [comment]
Hi @ruifortes I just released the version 1.2.1 of the add-on this morning, it now supports Blender 2.93 (you automatically get the update, on ths same gumroad page)

**Comment by ruifortes** [comment]
Perfect timing!! Thanks :-)

**Comment by martinsstuff** [comment]
I have the same issue in Blender 3.1.2 and TexturePacker v1.2.2, is there a way to check which Blender version it's compatible with?

**Comment by martinsstuff** [comment]
Update: The problem is Blender 3.1, 3.0 works fine.

**Comment by eliemichel** [comment]
Hello! Thanks for reporting this, I just added a version 1.2.3 on the Gumroad page to update to Blender 3.1!

**Comment by eliemichel** [comment]
It's been updated again 2 days ago for Blender 4.1 / Python 3.11!

**Comment by Madebyhafeez** [comment]
I am still having the same problem. I have tried to download different version of blender and also tested them with different versions of lilly.

But nothing is working, any help will absolutely go a long way
