### ISSUE TITLE
Lily texture packer - Want to send to Unreal Engine

### ISSUE THREAD

**Issue by vaseg** [eliemichel/MapsModelsImporter#176]
Hi,
I merged huge blender file by lily capture merger (somethin like 70+ .rdc files) and after it simple it by lily texture packer. For each static mesh (group of joined meshes each .rdc one static mesh)

i try create simple static mesh with one material (in hope that lily texture packer doing that) and send to Unreal Engine.

after export to UE, it create one static mesh with in my case 228 materials with same lilytexturepack texture..

Is this the way how to join it in one material wih only one UV map? (NON baking way becouse i have 70+ peace of model)

SM_var_3
M_var_3
T_var_3

thx

![lily_texture_packer_text](https://user-images.githubusercontent.com/74784370/123427440-ea87b280-d5c4-11eb-9997-f3e3392570d2.jpg)

**Comment by eliemichel** [comment]
(Replied on twitter, but FTR, use Ctrl+L > Link Materials right after using LilyTexturePacker to have all object use the same material)

**Comment by vaseg** [comment]
Thx, prefect.. And in case that you already have joined in one mesh. Turn on edit mode select press P and separate by Material.
So, you can now use ctrl + L.
THX @eliemichel
