### ISSUE TITLE
Scale and Units for .rdc Imports

### ISSUE THREAD

**Issue by hazelvr** [eliemichel/MapsModelsImporter#179]
Hello Elie Michel,

I have been using your importer and Lily addons for a some time now, and everything works beautifully, thanks for your hard work! However, I've been struggling to find a definitive scale factor that will translate the imported captures to real-world units.

By matching up a measured distance in Google Earth and Blender, I've been able to surmise that it must be around 48x, but lacking any kind of definitive number, I've been running into problems when trying to use captured data for GIS applications.

Furthermore, I've noticed that the different LODs import with different scale factors, 0.3906 for the lowest LOD, twice that for the next level up, and so forth. Is there some reason for this?

**Comment by eliemichel** [comment]
Hi @hazelvr 
Unfortunately, there is no consistency across captures when they come from different machines and different zoom factors and different areas of the globe, so the only reliable solution remains to measure a distance `d` in Blender and the same distance `D` on a map and apply a global scale by `D/d`.
