### ISSUE TITLE
Useless?

### ISSUE THREAD

**Issue by oppne** [eliemichel/MapsModelsImporter#18]
For google maps this would be useless as the google maps does not have a 3D function anymore?

**Comment by petrbahr** [comment]
They do have such a function. In my case,i had to enable hardware acceleration again in my google chrome,then fully update my graphic drivers (integrated ATI) and restart PC. The 3d view is ofcourse available only in Terrain layer mode.

**Comment by eliemichel** [comment]
Google Maps still has a 3D feature, if your hardware supports it.
