### ISSUE TITLE
Just having issue loading this up in Blender , the Console gives no info

### ISSUE THREAD

**Issue by zeak6464** [eliemichel/MapsModelsImporter#182]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - test.rdc [test.zip](https://github.com/eliemichel/MapsModelsImporter/files/7080363/test.zip)
 - NVIDIA GeForce GTX 1060
 - v0.4
 - RenderDoc 1.13 
 - Blender 2.93

**Comment by eliemichel** [comment]
This is not a capture from Google Maps nor anything near it.
