### ISSUE TITLE
No error messages while importing RDC file and nothing shows on screen after importing.

### ISSUE THREAD

**Issue by sachinlobo11** [eliemichel/MapsModelsImporter#187]
renderdoc v1.7
blender 2.93.5
rdc v0.4

Hi, when I import nothing happened do I need to change any setting in blender?
D3D11 api used in rendering.

**Comment by sachinlobo11** [comment]
Issue solved. By disabling gravity in blender.

**Comment by eliemichel** [comment]
FTR I doubt disabling gravity has any impact, it must have been something else. Anyway next time enable debug info (in the add-on's user preferences) and look into system console (Window > Toggle System Console) to get feedback to copy here.
