### ISSUE TITLE
API initialisation failed

### ISSUE THREAD

**Issue by sebbelese** [eliemichel/MapsModelsImporter#21]
I know that this is an issue with RenderDoc 1.1/1.2, but since it happens with several users, I thought that it would be interesting to open an issue to try to figure out/gather information on how to fix this. Please close this issue if you find that it should not be here.

As many others, I can perform a capture with RenderDoc v1.2, but then I receive the "API initialization failed" message. 

I use a AMD Radeon (TM) R9 M360 discrete graphic cards, with the latest drivers (15.20.1062.1004-150803a1-187674C). Is another version of the drivers likely to work, or do you think of any possible workaround?

I wonder if there is a way to get the following extensions if they are not included in the drivers:
`ARB_vertex_attrib_binding ARB_program_interface_query ARB_shading_language_420pack ARB_separate_shader_objects`

Attached is my log file:
[logFail.log](https://github.com/eliemichel/MapsModelsImporter/files/4184709/logFail.log)

**Comment by eliemichel** [comment]
Hi @sebbelese thanks for this detailed feedback, this is indeed a common issue, that I'm having trouble debugging because I don't have a machine on which reproducing it.

The log file is instructive, was this output when importing the rdc file using the add-on, in Blender's console? The core issue is indeed the lack of some extensions for replaying the rdc. If you are already running the last version of your driver, then there is no other way of getting those extensions.

In newer versions of RenderDoc, some extensions are emulated (it seems to have been a problem beyond the case of this maps model importer tool), so build a new renderdoc.dll/renderdoc.pyd (https://github.com/eliemichel/MapsModelsImporter/tree/master/blender/MapsModelsImporter/bin/win64)  relying on RenderDoc v1.6.

This can get fairly technical and I did not have time to do it so far (which is why the add-on still requires older versions of RenderDoc) but if somebody wants to give it a try, I can provide some support.

**Comment by sebbelese** [comment]
Thanks for your detailed answer.

The log is not the output from the Blender addon, but from RenderDoc when I try to open the performed capture in order to check what is inside. But I suppose it may be the same API function as the one used in you plugin to open the file.

When I have some time, I will try to do the capture with RenderDoc 1.6 and check if I can at least analyse the capture within RenderDoc.

**Comment by eliemichel** [comment]
Hi @sebbelese I just released a new version based on RenderDoc 1.6 that may help you: https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.2.0-rc1
Please let me now!

**Comment by sebbelese** [comment]
Many thanks for this update.

Up to now it is not very successful on my side, but I believe that this is mostly related to the RenderDoc step.

Even with RenderDoc 1.6, I still need to use _use-angle=gl_ and _chrome 70_. For any other combination, Renderdoc cannot inject into process (_API: OpenGLES (Not Presenting)_).

When capturing with RenderDoc 1.6, chorme 70 and use-angle=gl option, I can save a rdc (~21Mb) which cannot be imported into blender. The log for the plugin is:
```
Loading capture from C:\Users\XXXXXXX\Documents\test2.rdc...
Error: Could not find the beginning of the relevant 3D draw calls
```

But I cannot re-open the rdc in RenderDoc either, so I suspect that it is wrong. Hence, the issue is not related with your plugin. Here is the renderdoc log when opening the rdc:
```
RDOC 012308: [09:13:56]             core.cpp( 421) - Log     - RenderDoc v1.6 Windows 64-bit Release (0e7f772596035137416be01766c2d61205efc63e) loaded in replay application
RDOC 012308: [09:13:57]      crash_handler.h( 150) - Log     - Timer Waiting for crash handling server - 400.236 ms
RDOC 012308: [09:13:57]      crash_handler.h( 156) - Log     - Created crash-handling server \\.\pipe\RenderDocBreakpadServer9960558891217
RDOC 012308: [09:13:57]      crash_handler.h(  87) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer9960558891217
RDOC 012308: [09:13:58]      crash_handler.h(  96) - Warning - Couldn't connect to existing breakpad server
RDOC 012308: [09:13:58]      crash_handler.h( 150) - Log     - Timer Waiting for crash handling server - 252.922 ms
RDOC 012308: [09:13:58]      crash_handler.h( 156) - Log     - Created crash-handling server \\.\pipe\RenderDocBreakpadServer9960578196327
QTRD 012308: [09:13:58]       qrenderdoc.cpp(  88) - Log     - QRenderDoc initialising.
QTRD 012308: [09:13:58]       qrenderdoc.cpp(  91) - Log     - Running as administrator
RDOC 012308: [09:14:01]      crash_handler.h(  51) - Log     - Re-using crash-handling server \\.\pipe\RenderDocBreakpadServer9960578196327
RDOC 012308: [09:14:01]      crash_handler.h(  87) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer9960578196327
RDOC 012308: [09:14:02]     d3d11_replay.cpp( 118) - Log     - Running replay on AMD / AMD Radeon (TM) R9 M360 15.200.1062.1004
RDOC 012308: [09:14:02]     d3d12_replay.cpp( 135) - Log     - Running replay on AMD / AMD Radeon (TM) R9 M360 15.200.1062.1004
RDOC 012308: [09:14:04]    android_tools.cpp( 345) - Log     - Initialising adb using 'X:\XXXXXXX\RenderDoc_1.6_64/plugins/android/adb'
RDOC 012308: [09:14:04]        vk_replay.cpp(4021) - Log     - Created device.
RDOC 012308: [09:14:04]         vk_win32.cpp( 201) - Log     - Converted X:\XXXXXXXX\RenderDoc_1.6_64
RDOC 012308: [09:14:04]         vk_win32.cpp( 201) - Log     - Converted X:\XXXXXXXX\RenderDoc_1.6_64
QTRD 012308: [09:14:09]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange () 0
QTRD 012308: [09:14:09]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange () 0
RDOC 012308: [09:14:09]    android_tools.cpp( 360) - Log     - Started adb server
QTRD 012308: [09:14:14]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange (QUrl("file:///C:/Users/XXXXXXX/Documents/test2.rdc")) 1
RDOC 012308: [09:14:14]          rdcfile.cpp( 244) - Log     - Opening RDCFile C:/Users/XXXXXXX/Documents/test2.rdc
RDOC 012308: [09:14:14]          rdcfile.cpp( 244) - Log     - Opening RDCFile C:/Users/XXXXXXX/Documents/test2.rdc
RDOC 012308: [09:14:14]             core.cpp(  49) - Log     - Not enabling API validation during replay
RDOC 012308: [09:14:14]             core.cpp(  54) - Log     - Using default GPU replay selection algorithm
RDOC 012308: [09:14:14]             core.cpp(  63) - Log     - Replay optimisation level: Balanced
RDOC 012308: [09:14:14]        gl_replay.cpp(3663) - Log     - Creating an OpenGL ES replay device
RDOC 012308: [09:14:14]        gl_replay.cpp(3701) - Error   - libEGL not available, and GL cannot initialise or doesn't support EXT_create_context_es2_profile
RDOC 012308: [09:14:14] replay_controller.cpp(1996) - Error   - Couldn't create a replay device.
RDOC 012308: [09:14:14] replay_controller.cpp(  69) - Log     - Shutting down replay renderer
QTRD 012308: [09:14:30]              unknown(   0) - Debug   - QWindowsNativeFileDialogBase::onSelectionChange () 0
```

**Comment by sebbelese** [comment]
Thanks for this new release!

It is much better with RenderDoc 1.6 and without using angle. However, when I try to import the rdc in Blender, I get:
```
Loading capture from C:\Users\XXXXXXX\Documents\test4.rdc...
Error: Could not find the beginning of the relevant 3D draw calls
```
I am not sure that there is some 3d in my captures (although I tried several times). Rhere is no _DrawElement_ in the event browser. Does that mean that 3d was not captured?

![image](https://user-images.githubusercontent.com/16559668/74719092-abf52180-5233-11ea-9043-e6be3fcbddb5.png)

**Comment by eliemichel** [comment]
Your capture seems fine, `DrawIndexed` is what is expected when using DirectX (it is still using ANGLE, but with DirectX backend rather than OpenGL, to be exact). The problem is in finding the line before these DrawIndexed, that should be a "Clear something" but vary depending on the machine. Some such events are listed [here](https://github.com/eliemichel/MapsModelsImporter/blob/master/blender/MapsModelsImporter/google_maps_rd.py#L45) but as it depends on the GPU vendor the list is not complete yet. Could you find the exact name of this first event, ore provide my the rdc file?

**Comment by sebbelese** [comment]
Indeed, there is a ClearRenderTargetView and a ClearView:
![image](https://user-images.githubusercontent.com/16559668/74815013-b75e5080-52f8-11ea-80ed-259e43c4fd0b.png)

rdc is here: 
https://www.transfernow.net/v004G4022020

**Comment by eliemichel** [comment]
Try the new RC2: https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.2.0-rc2

**Comment by sebbelese** [comment]
Works perfectly!
