### ISSUE TITLE
unsupported command line in latest chrome

### ISSUE THREAD

**Issue by aeon3** [eliemichel/MapsModelsImporter#210]
![image](https://user-images.githubusercontent.com/7735301/156237393-76a8dcdc-d02e-404b-92c6-23f78c11a58e.png)

basically this. I have been experiencing a lot of glitches that were not there couple months ago. Is there a work around for that issue?

google maps opens all black and google earth glitches but still useable.

**Comment by eliemichel** [comment]
I have the same warning, it is still needed and working though (as of February 2023)
