### ISSUE TITLE
ETA on Blender 3.1?

### ISSUE THREAD

**Issue by ThinkWithPbody** [eliemichel/MapsModelsImporter#214]
Love this addon. Will it be made available for blender 3.1 or do we have to import models from 2.93?

**Comment by Peato88** [comment]
Please Port it to PY3.10! Would be nice to test it!

**Comment by eliemichel** [comment]
Here you are! https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.5.0-rc1
