### ISSUE TITLE
Chrome GPU PID Reset | Chrome 79, RenderDoc 1.13, MapsModelImporter 0.4, Windows 8.1

### ISSUE THREAD

**Issue by d-bracher** [eliemichel/MapsModelsImporter#215]
Similar problems as 

#147 
#123 

Whenever I try to inject into the Chrome process and access Google Maps, Chrome resets the PID for the GPU. After reentering the altered PID for a couple of times Google Maps starts without OpenGL features. Same for Microsoft Edge. Extracting 3D info is thus not possible. 

I tried with older versions of Chrome, but then the problem seems to be that Maps doesnt support OpenGL features with this browser versions (up to Chrome 80). Also tried changing my region, adding the --ignore-gpu-blacklist flag to Chrome Shortcut and add ?force=webgl to the browser query. No results. 

A year ago this worked fine, I think I worked with Chrome ~v.80 and RenderDoc 1.9. 

Versions I have tried

Render Doc 1.9, 1.10, 1.13
Chrome 70, 75, 79, 80, 100

For some reason I accidently managed to capture some 3D data with Google Chrome Version 70 I think. I couldnt reproduce. 

Somebody mentioned this might be due to an older graphics card. Could be the case. Lenovo U330p with a built in Intel i5 4200U.

Any help deeply appreciated, 4h straight spent with this issue and counting.

**Comment by P0isonousPurple** [comment]
Having the same problem. Worked with it yesterday and now it doesn't work. No update of RenderDoc or Chrome was made by me.
RenderDov v.18 / Chrome 100 / GPU: NVIDIA GeForce GTX 1060 6G

**Comment by P0isonousPurple** [comment]
> Found the solution in my case. I started Chrome not from within the cmd but with the modified default chrome shortcut. Changing to the cmd and typing the code found in the git pages by elimichel did the job. Good luck

That actually helped! Thanks a lot :D

**Comment by JhottMaster** [comment]
This seems to continue to happen even following @d-bracher's instruction- though maybe I didn't use the right command. Here's an example of what my edited Google Chrome shortcut looks like:
`C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog"`

Any ideas of what else I could try?

**Comment by JhottMaster** [comment]
Ahh- never mind- make sure you don't have any _other_ running processes of Chrome or windows. Closing all existing windows/processes and then starting from scratch resolved my issue.

**Comment by P0isonousPurple** [comment]
@d-bracher please close this issue :D

**Comment by Timmmm** [comment]
Maybe note this in the instructions? Pretty hard to find.

**Comment by Timmmm** [comment]
Also @JhottMaster 's solution didn't work for me. It still restarts the GPU process a few times but then it seems to give up and when I went to Google Maps, 3D was disabled entirely.
