### ISSUE TITLE
 Error: Could not find the beginning of the relevant 3D draw calls

### ISSUE THREAD

**Issue by royalboi** [eliemichel/MapsModelsImporter#22]
Everytime i try to import, it say
" Error: Could not find the beginning of the relevant 3D draw calls"

Im using Window 10, 1060ti, RenderDoc 1.6, Map import 0.2.0, Chrome 80.
Tried several Broswer like Chrominum, Vivaldi... but still not working

I tried previous version at last night but always get Couldn't initialise replay and i'm so surprised that you got new version when i just discover it, but i think no luck for me :(

**Comment by royalboi** [comment]
[](https://we.tl/t-svu9FXF1Fr
)
This is my rdc file

**Comment by royalboi** [comment]
Tested on 1080ti, still have the same error!!!

**Comment by eliemichel** [comment]
Thanks a lot for the rdc, it helped me fixed to bugs, namely yours and a gradient texture issue. Try the new RC2: https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.2.0-rc2
