### ISSUE TITLE
can't open the file properly in blender

### ISSUE THREAD

**Issue by helinhalis** [eliemichel/MapsModelsImporter#220]
Blender 3.1.2
RenderDoc 1.19
MapsModelsImporter v0.5.0

After import the rdc file in blender, I get the output like this. The 3D image does not appear. What could be the reason for this? 

![Adsız](https://user-images.githubusercontent.com/49252442/168908725-4d797ec2-efb6-4e24-a912-ae6fc85eede0.png)

**Comment by helinhalis** [comment]
with different .rdc file

![Adsız2](https://user-images.githubusercontent.com/49252442/168910445-3069abd5-a050-4102-8e71-4f696c82b95d.png)

**Comment by eliemichel** [comment]
In the first case it seems that the capture contains such a big chunk of earth that the area of interest appears very small. Try taking teh capture from a more vertical view direction and don't browse the whole planet before taking the capture. The second capture is likely taken w/o 3D or from a wrong version of RenderDoc.

**Comment by helinhalis** [comment]
Thank you for the information
