### ISSUE TITLE
After  "Inject the Process" is run and click ok for PID the tab disappearing

### ISSUE THREAD

**Issue by ManPython** [eliemichel/MapsModelsImporter#222]
After  "Inject the Process" is run and click ok for PID GPU for msedge or chrome GPU, the card to cappture sequentional frame disappearing with tab and must do process again, but with no any sucess.

 - The .rdc file
 - Your GPU gtx650ti
 - Version of this add-on (must be the most recent one)
 - Version of RenderDoc (1.13 recommended) - RenderDoc_1.13_64 (Works time ago - 6months ago), RenderDoc_1.20_64
 - Version of Blender (2.93 recommended)
 - Edge 102.0.1245.30 
 - Chrome 102.0.5005.63 

Hmm.. for chrome google maps disabled 3d maps globe : )

I want propose the 3d ripper for earth web or app like for Sketchfab etc ;p

**Comment by eliemichel** [comment]
Try using the versions suggested in [the last release notes](https://github.com/eliemichel/MapsModelsImporter/releases/latest) (I fixed the issue template that was giving outdated versions).

**Comment by ManPython** [comment]
Can you confirm that still working?

**Comment by eliemichel** [comment]
I confirm! Captured today:

![image](https://user-images.githubusercontent.com/5802849/173097415-2d91efbb-3703-4960-8265-2c2ae6cb4b07.png)

**Comment by ManPython** [comment]
> I confirm! Captured today:

Are you sure that you using new scripts from Chrome or Edge and not cached on your browser?

**Comment by nosy-b** [comment]
Ok Sorry my bad, it works now. It can also be the reason for you @ManPython and @JohnR777 : 

   **Make sure chrome was completely stopped before starting the custom shortcut**

**Comment by JohnR777** [comment]
My issue was Edge... went back to chrome and version 1.13 and all us well

**Comment by ManPython** [comment]
102.0.5005.115 failed
`Core 12104 19:11:26 win32_process.cpp(947) Error Can't locate renderdoc.dll in remote PID 14864`
```Core 6616 19:22:08 core.cpp(459) Log   RenderDoc v1.13 Windows 64-bit Release (cc05b288b6d1660ab04c6cf01173f1bb62e6f5dd) loaded in replay application
Core 6616 19:22:08 core.cpp(470) Warning Couldn't open socket for target control           
Core 13908 19:22:08 core.cpp(459) Log   RenderDoc v1.13 Windows 64-bit Release (cc05b288b6d1660ab04c6cf01173f1bb62e6f5dd) loaded in replay application
Core 13908 19:22:08 core.cpp(470) Warning Couldn't open socket for target control
```
103.0.5060.66 failed - this same

**Comment by heikog** [comment]
same here. 
Windows 11
RenderDoc 1.19 
Chrome 108.0.5359.22

As soon as I click the ok Button in Chrome the tab in RenderDoc goes away

**Comment by eliemichel** [comment]
If on a laptop with 2 graphics device, can you check that both Chrome and RenderDoc run on the same one (preferably the dedicated device)?

**Comment by ManPython** [comment]
It's working for You? 
Did You updated RenderDoc or Chrome? I can repat on this same configuration like You have.
Last time I spent with many variation but don't know what is spared actually as correct to working.

**Comment by ManPython** [comment]
Confirming this: `Use version 0.6.0 (for RenderDoc 1.25 and Blender 3.4) or newer!` as actual?

**Comment by ManPython** [comment]
Maybe this can be simplified by https://chromedriver.chromium.org/getting-started with addin some "bunde" or "pack" that working and can't be updated?

**Comment by ManPython** [comment]
After many experiments.. tests.. can't find success as time ago.
Also tried portable and working.
https://sourceforge.net/projects/portableapps/files/Google%20Chrome%20Portable/GoogleChromePortable64_110.0.5481.97_online.paf.exe/download
