### ISSUE TITLE
RenderDoc v1.19 has no 'Inject Into process'?

### ISSUE THREAD

**Issue by Iasius** [eliemichel/MapsModelsImporter#226]
Hi, I'm using the recommended versions of Blender (3.1) and RenderDoc (1.19) for [Maps Models Importer v0.5.0-rc1](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.5.0-rc1)

But there is no File-Inject into process button for this version, how do I proceed with v0.5.0?

**Comment by JohnR777** [comment]
Check the settings page of renderdoc, the tickbox to enable it is there

**Comment by Tumppa** [comment]
Thank you for your help. It's so easy. But hard if you don't know where to look.
