### ISSUE TITLE
limited to 200 meshes on import

### ISSUE THREAD

**Issue by flohock** [eliemichel/MapsModelsImporter#23]
Hi, 

I noticed that when importing data from google in Blender it seems to stop to the mesh called BuildingMesh-00199

It's enough when you get a standard capture but when you increase the quality in google maps (higher LODs are loaded if you have a bigger window size, and you can trick by asking chrome to reduce the zoom to 25% for the best possible quality) it becomes rapidly insufficient and you can only load the very first meters of the capture.

It would be awesome if we could load more meshes from the capture, as the standard resolution does not even offer the best lods in the foreground.

You can find my tests on the same view of New York City and how it imports in Blender 2.81. Let me know when you got it, I will need to free space on my google drive sooner or later. :D
[https://drive.google.com/open?id=135sTbRbkPqIJ0a7IEOw2fwIh7uovt5nV](https://drive.google.com/open?id=135sTbRbkPqIJ0a7IEOw2fwIh7uovt5nV)

Anyway thanks for your time and your awesome tool and guide!

**Comment by flohock** [comment]
I'm just realising that I'm using the 0.1.3 version I downloaded yesterday morning. I didn't expect a new version to be released later that same day. 

I Also see a  "settings.png" file with "max blocks" option set to "200" which might be the option to set to solve my problem.

I'll try with the new version, and tweak this setting.

**Comment by flohock** [comment]
Alright,

Indeed, this issue was caused by the "Max Blocks" settings set to "200" by default on import. I just didn't notice there were any option on import at first, probably because i'm not used to blender yet.

Sorry for the inconvenience of opening a ticket for nothing. :/

**Comment by eliemichel** [comment]
No problem, it's a limit to prevent Blender from freezing too long the first time one tries the process, but since you are not the only one to get tricked by it I wonder if I should set it to -1 (no limit) by default.

**Comment by flohock** [comment]
Not sure... When I tried with higher resolution, it was indeed very long (more than 3.3k blocks).

Maybe the best would be insisting on the max number of block option for blender newbies. But it's only a problem when you do a capture with a high resolution anyway (like with a 4k screen) or with the trick I mentioned. With a 1920*1080 resolution I had 230 block or so, meaning that only the very far ones, revealing the curvature of the earth are not visible which is usually not a problem.

It might just be a side note on the HowTo somewhere. Something like that for instance :

"If you want better quality captures, you should know that google maps loads LoDs (Levels of Details) in relation with the window size of your web browser. There is several way to increase it :
 - You can increase your screen resolution. Also note that nvidia allows now to increase the rendering resolution of your screen to 4k even with a simple full HD screen.
- You can also use the rendering size percentage in google chrome. Most browsers do offer the option to zoom in or out the web pages to adapt them to your screen resolution. By setting the zoom at 25% in Google Chrome, you also increase the level of detail.

But while doing so you also increase dramatically the number of block. Beware of that as the Blender GoogleMapsImporter is set to 200 blocks to import by default to prevent from freezing for too long. You can change this number on import but be aware that you'll have to wait much more for the import to be complete."

Anyway have a nice day, and I'm pretty happy to have been able to import that on unreal. I don't know what I'll do with that but it's pretty cool to navigate through a real size low poly Manhattan. 
So thanks again for your tool and sharing your knowledge.

**Comment by eliemichel** [comment]
Well, this limit is already mentionned in the [YouTube video](https://www.youtube.com/watch?v=X6Q7dbtXVZQ) and in the [README #missing-blocks](https://github.com/eliemichel/MapsModelsImporter#missing-blocks). I'll add your remark in the troubleshooting section, thx for the suggestion.
