### ISSUE TITLE
Can not start chrome using the provided command

### ISSUE THREAD

**Issue by EdwardDeaver** [eliemichel/MapsModelsImporter#233]
Chrome version: Version 103.0.5060.134 (Official Build) (64-bit)

When I try to run this command: set RENDERDOC_HOOK_EGL=0
"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-gpu-sandbox --gpu-startup-dialog

I get the following error messages. This was working yesterday and today it doesn't work...

When I run in CMD I get this message:

Set-Variable : A positional parameter cannot be found that accepts argument '--disable-gpu-sandbox'.
At line:1 char:1
+ set RENDERDOC_HOOK_EGL=0 "C:\Program Files (x86)\Google\Chrome\Applic ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Variable], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetVariableCommand

When I try running it via the Windows Run dialogue:
Windows cannot find 'set'. Make sure you typed the name correctly, and then try again.

I'm not sure what changed between today and yesterday but the set command doesn't seem to work now.

**Comment by saiidabs** [comment]
user Microsoft edge, https://www.youtube.com/watch?v=03eOMedh8Ts
