### ISSUE TITLE
API: none when injecting into process on chrome/renderdoc

### ISSUE THREAD

**Issue by RedditStuffer** [eliemichel/MapsModelsImporter#234]
I get the text box, I find the correct selection in renderdoc, it opens the page on renderdoc, but it has API: none and then closes immediately after closes the chrome textbox.

**Comment by RedditStuffer** [comment]
I have even downloaded older versions of render doc to try and go through that process. I am apprehensive to go back in times as far as chrome, and don't know what to put in the properties section if I use Microsoft edge.

**Comment by mfeldt** [comment]
I guess it's more about the chrome version. Current versions give a message about the flag --disable-gpu-sandbox not being supported, and when this occurs the connection does not work in my experience.  Edge is much the same I think - is it not actually chrome anyway?

**Comment by RedditStuffer** [comment]
> I guess it's more about the chrome version. Current versions give a message about the flag --disable-gpu-sandbox not being supported, and when this occurs the connection does not work in my experience. Edge is much the same I think - is it not actually chrome anyway?

I think I am going to use my non primary laptop, and install an older version of chrome on there and see what happens. I will just match the chrome version from the tutorial copy, so I can isloate if it is a software issue, or maybe a hardware issue (but considering I have tried 3 different computers with 3 different gpu's, I doubt it).

**Comment by mfeldt** [comment]
I was lucky yesterday with a chromium downloaded from here: 

http://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/1000015/

Simply unpack the chrome-win.zip somewhere, place a shortcut to the executable on your desktop and modify the target as usual.

**Comment by RedditStuffer** [comment]
I figured out there there was a program deep in my boot processes that ran off Chrome stealthily. I only realized it when I went to uninstall chrome and there was a background process using chrome without the chrome logo. That was holding up the api.
