### ISSUE TITLE
Importing RDC file from MacOS?

### ISSUE THREAD

**Issue by EdwardDeaver** [eliemichel/MapsModelsImporter#235]
Hello, 

Is it possible to import the RDC file created by RenderDoc on a Windows machine, in Blender using MacOS?

When I tried I saw the addon is looking for RenderDoc.

**Comment by mac4kent** [comment]
Yes true they said that.
I do use Macintosh on MacOS 13.xx plus Blender 3.4.1 and 3.5.0 too only way to use Mac. Do not use Windows.

**Comment by eliemichel** [comment]
The thing is the add-on has a component that is build from C++, and I do not have a Mac to build this part of the addon for Mac, so no it does not work, unless you build the python module from this custom branch of RenderDoc for Mac: https://github.com/eliemichel/renderdoc/tree/blender-v1.25
