### ISSUE TITLE
can't import .rdc  into blender 2.82 

### ISSUE THREAD

**Issue by mehi123maybe** [eliemichel/MapsModelsImporter#25]
hello
i tried to import .rdc  file intor blender and ran into this error :
i used addon v1.2 and v2 both have same problem

> 
> Traceback (most recent call last):
>   File "C:\Users\m\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
>     importCapture(context, self.filepath, self.max_blocks, pref)
>   File "C:\Users\m\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 179, in importCapture
>     mat_name = "BuildingMat-{:05d}".format(drawcallId)
>   File "C:\Users\m\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 41, in captureToFiles
>     python = os.path.join(python_home, "bin", "python.exe" if sys.platform == "win32" else "python3.7m") # warning: hardcoded python version for non-windows might fail with Blender update
>   File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\subprocess.py", line 472, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\lib\subprocess.py", line 1178, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> location: <unknown location>:-1
> 
>

**Comment by eliemichel** [comment]
Can you locate `python.exe` in `C:\Program Files\Blender Foundation\Blender 2.82`?

**Comment by mehi123maybe** [comment]
excuse me , the problem was i save the map in the wrong way ( didn't know Google map should be in  globe mode at first)
now it's working fine 
thank you
