### ISSUE TITLE
Problem at stage: no possible to inject into process from renderdoc v.1.19 to open Chrome

### ISSUE THREAD

**Issue by LuminousNFC** [eliemichel/MapsModelsImporter#252]
Subject - [Maps Models Importer v0.5.0](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.5.0)

Problem at stage: no possible to inject into process from renderdoc v.1.19 to open Chrome

Gpu starting with pid: 10252
Error message comes on chrome page: 
Error injecting into process 10252 for capture 
Process is incompatible with this build of renderdoc. Check the diagnostic log in the help for more details.

I went through all configuration possibility you propose, I am close to success, could you please help.
I am not an expert, thanks a lot and best regards

Blender 3.3.2 has accepted the Mapsmodels importer and is selected
Renderdoc v1.19
Google Chrome Version 108.0.5359.125 (Build officiel) (64 bits) install date 07.01.23

**Comment by LuminousNFC** [comment]
diag log:
Core PID  14504: [16:34:10]core.cpp(496) - Warning - Couldn't open socket for target control
UI PID  14504: [16:34:10] ToolWindowManager.cpp(1544) - Warning - area parameter ignored for this type
In red
core 14505 win32_process.cpp(704) Error can't capture x64 process with x86

**Comment by eliemichel** [comment]
Indeed, there was a problem with RD 1.19, so I just released a new version based on RD 1.25! https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.6.0
