### ISSUE TITLE
Cannot import RDC  file and no error message on the MapsModelsImporter

### ISSUE THREAD

**Issue by hhh3h** [eliemichel/MapsModelsImporter#254]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file
 - Your GPU name: Intel(R) Core(TM) i7-12700   2.10 GHz
 - Version of this add-on: 0.4
 - Version of RenderDoc: 1.13
 - Version of Blender: 3.0
 - 
It's not possible to import the RDC file but no error(info) messages on it.
So I don't know why it is not possible.

Plz, refer to attachment !!
[https://github.com/hhh3h/tests/blob/master/222.rdc](url)

Before even reporting, make sure that you are using [the last version](https://github.com/eliemichel/MapsModelsImporter/releases/latest) of this add-on and that you stick to the version of Blender and RenderDoc indicated in the release notes of this last version!

**Comment by eliemichel** [comment]
February 2023:
 - Use version [0.6.0](https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.6.0) of this add-on
 - Use RenderDoc v1.25
 - Use Blender 3.4

**Comment by hhh3h** [comment]
same,
plz refer to https://github.com/hhh3h/tests/blob/master/test4.rdc
