### ISSUE TITLE
Cannot import RDC  file and no error message on the MapsModelsImporter w/ latest versions as well

### ISSUE THREAD

**Issue by hhh3h** [eliemichel/MapsModelsImporter#255]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

- The .rdc file
- Your GPU name: Intel(R) Core(TM) i7-12700 2.10 GHz
- Version of this add-on: 0.6
- Version of RenderDoc: 1.25
- Version of Blender: 3.4
It's not possible to import the RDC file but no error(info) messages on it.
So I don't know why it is not possible.

Plz, refer to attachment !!
[https://github.com/hhh3h/tests/blob/master/test4.rdc](https://github.com/eliemichel/MapsModelsImporter/issues/url)

Before even reporting, make sure that you are using [the last version](https://github.com/eliemichel/MapsModelsImporter/releases/latest) of this add-on and that you stick to the version of Blender and RenderDoc indicated in the release notes of this last version!

**Comment by eliemichel** [comment]
You were not in 3D mode when taking this capture, make sure to enable the Globe view in Maps, if you don't see 3D in Maps the capture will not contain any 3D data.

**Comment by hhh3h** [comment]
> You were not in 3D mode when taking this capture, make sure to enable the Globe view in Maps, if you don't see 3D in Maps the capture will not contain any 3D data.

I made it as a Globe view already.
Could you import test4.rdc  file in your blender?

**Comment by eliemichel** [comment]
I could not import test4.rdc in Blender but I could open it in RenderDoc and I'm 100% positive about the fact tha globe view was not enabled. Sattelite view was, but these were only 2D pictures, not 3D data, you need to be able to rotate the view with Ctrl/Cmd+mouse
