### ISSUE TITLE
Invalid RDC capture file

### ISSUE THREAD

**Issue by AliAlherz64** [eliemichel/MapsModelsImporter#257]
when I try to import attached (compressed) file, I get error [Invalid RDC capture file].
[Haramain_20230207.zip](https://github.com/eliemichel/MapsModelsImporter/files/10709333/Haramain_20230207.zip)

RenderDoc capturing log:

RDOC 020124: [17:06:57]             [core.cpp( 499)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/core/core.cpp#L499) - Log     - RenderDoc v1.25 Windows 64-bit Release (d47e79ae079783935b8857d6a1730440eafb0b38) loaded in replay application
RDOC 020124: [17:06:58]      [crash_handler.h( 150)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/core/crash_handler.h#L150) - Log     - Timer Waiting for crash handling server - 101.047 ms
RDOC 020124: [17:06:58]      [crash_handler.h( 156)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/core/crash_handler.h#L156) - Log     - Created crash-handling server \\.\pipe\RenderDocBreakpadServer8717118699552
RDOC 020124: [17:06:58]      crash_handler.h(  87) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer8717118699552
RDOC 020124: [17:06:58]         [settings.cpp( 460)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/core/settings.cpp#L460) - Log     - Loading config from C:\Users\Ali AlHarz\AppData\Roaming\renderdoc\renderdoc.conf
QTRD 020124: [17:06:58]       [qrenderdoc.cpp( 166)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/qrenderdoc/Code/qrenderdoc.cpp#L166) - Log     - QRenderDoc initialising.
RDOC 020124: [17:06:58]             [core.cpp( 613)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/core/core.cpp#L613) - Log     - Replay application 'C:\Program Files\RenderDoc\qrenderdoc.exe' launched
RDOC 020124: [17:06:58]      crash_handler.h(  51) - Log     - Re-using crash-handling server \\.\pipe\RenderDocBreakpadServer8717118699552
RDOC 020124: [17:06:58]      crash_handler.h(  87) - Log     - Connecting to server \\.\pipe\RenderDocBreakpadServer8717118699552
RDOC 020124: [17:06:58]     [d3d11_replay.cpp( 143)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/driver/d3d11/d3d11_replay.cpp#L143) - Log     - Running replay on Intel / Intel(R) HD Graphics 630 30.0.101.1692
RDOC 020124: [17:06:58] [d3d12_sdk_select.cpp( 373)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/driver/d3d12/d3d12_sdk_select.cpp#L373) - Log     - System D3D12 runtime is version 2

RDOC 020124: [17:06:58]     [d3d12_replay.cpp( 112)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/driver/d3d12/d3d12_replay.cpp#L112) - Log     - Running replay on Intel / Intel(R) HD Graphics 630 30.0.101.1692
RDOC 020124: [17:06:58]        [vk_replay.cpp(4702)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/driver/vulkan/vk_replay.cpp#L4702) - Log     - Created device.
RDOC 020124: [17:06:59]    [android_tools.cpp( 347)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/android/android_tools.cpp#L347) - Log     - Initialising adb using 'C:\Program Files\RenderDoc/plugins/android/adb'
QTRD 020124: [17:06:59] ToolWindowManager.cpp(1548) - Warning - area parameter ignored for this type
RDOC 020124: [17:07:04]    [android_tools.cpp( 362)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/android/android_tools.cpp#L362) - Log     - Started adb server
RDOC 020124: [17:07:15]          [rdcfile.cpp( 250)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/serialise/rdcfile.cpp#L250) - Log     - Opening RDCFile D:/Blender Projects/Atabatain/RenderDoc/Haramain_20230207.rdc
RDOC 020124: [17:07:15]          [rdcfile.cpp( 250)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/serialise/rdcfile.cpp#L250) - Log     - Opening RDCFile D:/Blender Projects/Atabatain/RenderDoc/Haramain_20230207.rdc
RDOC 020124: [17:07:15]             core.cpp(  59) - Log     - Not enabling API validation during replay
RDOC 020124: [17:07:15]             core.cpp(  64) - Log     - Using default GPU replay selection algorithm
RDOC 020124: [17:07:15]             core.cpp(  73) - Log     - Replay optimisation level: Balanced
RDOC 020124: [17:07:15]     [d3d11_replay.cpp(4055)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/driver/d3d11/d3d11_replay.cpp#L4055) - Log     - Capture was created on Intel / Intel(R) HD Graphics 630
RDOC 020124: [17:07:15]      [dxgi_common.cpp(2030)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/driver/dxgi/dxgi_common.cpp#L2030) - Log     - Selected Intel / Intel(R) HD Graphics 630 adapter for replay
RDOC 020124: [17:07:15]     [d3d11_replay.cpp(4379)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/driver/d3d11/d3d11_replay.cpp#L4379) - Log     - Created device.
RDOC 020124: [17:07:15]     [d3d11_replay.cpp( 143)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/driver/d3d11/d3d11_replay.cpp#L143) - Log     - Running replay on Intel / Intel(R) HD Graphics 630 30.0.101.1692
RDOC 020124: [17:07:15]     [d3d11_replay.cpp( 243)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/driver/d3d11/d3d11_replay.cpp#L243) - Log     - Intel GPU detected - trying to initialize Intel counters
RDOC 020124: [17:07:15] [replay_controller.cpp(2114)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/replay/replay_controller.cpp#L2114) - Log     - Created replay driver.
RDOC 020124: [17:07:16]     [d3d11_device.cpp(1348)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/driver/d3d11/d3d11_device.cpp#L1348) - Log     - Timer chunk initialisation - 120.320 ms
QTRD 020124: [17:07:16]    [ReplayManager.cpp( 464)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/qrenderdoc/Code/ReplayManager.cpp#L464) - Log     - QRenderDoc - renderer created for "D:/Blender Projects/Atabatain/RenderDoc/Haramain_20230207.rdc"
RDOC 020124: [17:12:19]          [rdcfile.cpp( 250)](https://github.com/baldurk/renderdoc/blob/d47e79ae079783935b8857d6a1730440eafb0b38/renderdoc/serialise/rdcfile.cpp#L250) - Log     - Opening RDCFile D:/Blender Projects/Atabatain/RenderDoc/Haramain_20230207.rdc

**Comment by AliAlherz64** [comment]
Blender debug log:


Read prefs: C:\Users\Ali AlHarz\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
google_maps_rd returned:
C:\Users\Ali AlHarz\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\MapsModelsImporter\google_maps_rd.py:62: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([array.ndim], dtype=np.int).tofile(file)
C:\Users\Ali AlHarz\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\MapsModelsImporter\google_maps_rd.py:63: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(array.shape, dtype=np.int).tofile(file)
Loading capture from D:\Blender Projects\Atabatain\RenderDoc\Haramain_20230207.rdc...
Trying scraping strategy #4...
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall 109))
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: 109)
Trying scraping strategy #5...
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: 109)
Trying scraping strategy #6...
Not relevant yet: Draw()
Not relevant yet: Draw()
Trying scraping strategy #7...
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: DrawIndexed()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: DrawIndexed()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: DrawIndexed()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: DrawIndexed()
Not relevant yet: Draw()
Not relevant yet: DrawIndexed()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: 109)
Trying scraping strategy #8...
(Skipping drawcall Draw())
Scraping capture from Google Maps...
Warning: No texture found for drawcall 0
Profiling counters:
 - consolidateEvents: 0.146ms (±0.0ms, 1 samples)
 - extractRelevantCalls: 28.0ms (±0.0ms, 1 samples)
 - extractTexture: 0.0859ms (±0.0ms, 1 samples)
 - processDrawEvent: 16.8ms (±0.0ms, 1 samples)

globUniforms:
  _sk_RTAdjust: (0.125, -1.0, 0.03125, -1.0)

**Comment by AliAlherz64** [comment]
This is log when i used delayed capture:


Read prefs: C:\Users\Ali AlHarz\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
Info: Deleted 1 object(s)

google_maps_rd returned:
Loading capture from D:\Blender Projects\Atabatain\RenderDoc\Haramain_20230210.rdc...
Trying scraping strategy #4...
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall 138))
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: 138)
Trying scraping strategy #5...
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: 138)
Trying scraping strategy #6...
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: 138)
Trying scraping strategy #7...
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: 138)
Trying scraping strategy #8...
(Skipping drawcall Draw())
(Skipping drawcall Draw())
(Skipping drawcall 138))
Error: Could not find the beginning of the relevant 3D draw calls
Scraping capture from none...
Profiling counters:
 - consolidateEvents: 0.0984ms (±0.0ms, 1 samples)
 - extractRelevantCalls: 0.0542ms (±0.0ms, 1 samples)

Profiling counters:

==========================================================

 this log when I reinject to same process of chrome again, which gave me meshes of ground:

Read prefs: C:\Users\Ali AlHarz\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
Info: Deleted 1 object(s)

google_maps_rd returned:
C:\Users\Ali AlHarz\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\MapsModelsImporter\google_maps_rd.py:62: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([array.ndim], dtype=np.int).tofile(file)
C:\Users\Ali AlHarz\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\MapsModelsImporter\google_maps_rd.py:63: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(array.shape, dtype=np.int).tofile(file)
Loading capture from D:\Blender Projects\Atabatain\RenderDoc\Haramain_20230210_b.rdc...
Trying scraping strategy #4...
(Skipping drawcall ClearDepthStencilView())
(Skipping drawcall Draw())
(Skipping drawcall Draw())
Not relevant yet: ClearRenderTargetView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: DiscardView()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: 138)
Trying scraping strategy #5...
Not relevant yet: ClearDepthStencilView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: DiscardView()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: 138)
Trying scraping strategy #6...
Not relevant yet: ClearRenderTargetView()
Not relevant yet: ClearDepthStencilView()
Trying scraping strategy #7...
Not relevant yet: ClearRenderTargetView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: DrawIndexed()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: ClearDepthStencilView()
Not relevant yet: DiscardView()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: Draw()
Not relevant yet: 138)
Trying scraping strategy #8...
(Skipping drawcall ClearDepthStencilView())
Scraping capture from Google Maps...
Profiling counters:
 - consolidateEvents: 0.629ms (±0.0ms, 1 samples)
 - extractRelevantCalls: 95.0ms (±0.0ms, 1 samples)
 - SaveTexture: 21.6ms (±1.68ms, 105 samples)
 - extractTexture: 21.7ms (±1.7ms, 105 samples)
 - processDrawEvent: 40.2ms (±2.86ms, 105 samples)

Profiling counters:
 - loadData: 6.55ms (±0.304ms, 105 samples)
 - processData: 0.877ms (±0.246ms, 105 samples)
 - addMesh: 1.01ms (±0.232ms, 105 samples)

===============================================
look to the error message in chrome:
![image](https://user-images.githubusercontent.com/96901891/218175186-1bbac4ff-abcd-4bf9-bf7d-0b2b9be7f5c4.png)

**Comment by eliemichel** [comment]
The problem is that you were not in Globe view when taking the capture (if you don't see 3D in Maps, you won't get 3D out of the capture)

**Comment by AliAlherz64** [comment]
Thanks eliemichel for your reply.

I am attaching screen shot of fresh captured file, to show 3D in google maps. also I attached screen shot of blender as well.
note: i changed zipped file ext, rar to zip.

![image](https://user-images.githubusercontent.com/96901891/218330535-932cedab-8c5e-4a17-97ae-69f863f4e09d.png)

![image](https://user-images.githubusercontent.com/96901891/218331004-291f8de5-c864-483e-af3e-2c7ad88ce0b1.png)


[Abu Fadhl Al-Abbas.zip](https://github.com/eliemichel/MapsModelsImporter/files/10716930/Abu.Fadhl.Al-Abbas.zip)

**Comment by AliAlherz64** [comment]
I think , got it, just look to those 2 screenshots, it seems that google deleted 3D data for this zone

![image](https://user-images.githubusercontent.com/96901891/218334017-563752ad-0672-4cda-ad50-5e7309035e9c.png)

![image](https://user-images.githubusercontent.com/96901891/218334153-032b8795-4aab-47d9-9e67-bd68a5da9c03.png)

regards

**Comment by eliemichel** [comment]
Yes unfortunately the quality of Google's 3D data is enequal across the globe, some regions are still mostly plane photos projected onto coarse elevation maps
