### ISSUE TITLE
Chrome API does not activate in RenderDoc

### ISSUE THREAD

**Issue by riccardocrosa** [eliemichel/MapsModelsImporter#258]
All the applications that use, are up to date and I use this link to open Chrome

C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog"

but a white Chrome window never appears in addition to the Google Chrome GPU popup, but it opens a window with the sites that were open when I closed the previous Chrome window.

When after injection [photo 1](https://drive.google.com/file/d/1ViiLUDZ5uyJ_bBR47JJc5lbyiVvL4e3X/view?usp=share_link), I click OK on the Google Chrome GPU popup in RenderDoc the API does not activate and closes and what you see in [photo 2](https://drive.google.com/file/d/1tuJLEQlzmehIiNJ1dSMW9GYhVq4SjLXD/view?usp=share_link) appears. 

What can I do? Thanks

**Comment by eliemichel** [comment]
Did you make sure that RD and Chrome run on the same GPU? If you have a laptop with integrated chip + true GPU it happens that they run on a different device

**Comment by ManPython** [comment]
What type GPU You have? If NVIDIA then in control panel add renderdoc for GPU not integrated.
If not helping, try this version chrome.
https://github.com/eliemichel/MapsModelsImporter/issues/222#issuecomment-1430172510

**Comment by riccardocrosa** [comment]
Thank you I have solved the issue.

**Comment by ManPython** [comment]
With success as import to Blender?
