### ISSUE TITLE
Faulty Textures

### ISSUE THREAD

**Issue by flxpx** [eliemichel/MapsModelsImporter#26]
Hey Elie - first of all: thank you very much! This is awesome!

Sometimes the textures would not load correctly although they seem to be fine in the RenderDoc Viewer - what is loaded are png texture stripes 8x128px.

Could be a a Bug on the RenderDoc side too since every once in a while a .rdc would just not load into blender...

![NYC1-00002-texture](https://user-images.githubusercontent.com/61229101/74822086-debb1a80-5304-11ea-93e9-023c0ee9ca69.png)

Best wishes,
Felix

**Comment by eliemichel** [comment]
Indeed, I was working on this. Try the RC3: https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.2.0-rc3

(In the furture, please provide rdc files when reporting such issue ;) )

**Comment by flxpx** [comment]
Awesome, thank you. Will do in the future.
