### ISSUE TITLE
After importing nothing shows in Blender workspace

### ISSUE THREAD

**Issue by bratkrk** [eliemichel/MapsModelsImporter#27]
After import to Blender, nothing shows.

I check in RenderDoc how Capturing goes and there is a lot of textures mesh etc.
But after saving I trying to import to Blender, after 30sec I have just plain workspace.

I have Radeon R9 380 its the issue?

Many thanks for all You doing.

Console 
Read prefs: C:\Users\..\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.80\python
Info: Deleted 1 object(s)

Loading capture from C:\..\City2.rdc...
Draw call: ClearDepthStencilView(D=1.000000, S=00)
(Skipping)
Draw call: DrawIndexed(2160)
Draw call: DrawIndexed(2300)
Draw call: DrawIndexed(1727)
...
Draw call: DrawIndexed(3505)
Draw call: DrawIndexed(993)

Try to import capture.rdc - test capture found at github and get error like this:

Loading capture from C:\Users\..\Desktop\capture.rdc...
Couldn't initialise replay: 14
Traceback (most recent call last):
  File "C:\Users\Matt\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 182, in <module>
    main(controller)
  File "C:\Users\Matt\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 75, in main
    drawcalls = controller.GetDrawcalls()
AttributeError: 'NoneType' object has no attribute 'GetDrawcalls'

**Comment by eliemichel** [comment]
capture.rdc is outdated, I should replace it. It is weird that you have no error after the "Draw call:" lines. Can you provide the rdc file?

**Comment by bratkrk** [comment]
Can You send Me any working file I will check that is somthing wrong with blender or capturing.
 
My city rdc file:
https://drive.google.com/open?id=1mSmzSGT_o82-egLivSR4In9MJISUmFt_

Thanks Matt

**Comment by eliemichel** [comment]
Here is one:
https://wetransfer.com/downloads/08b239bc5ad46b3412a4f7e75171935520200223074823/4d1cedd883041de27d861eb4ba0f187820200223074835/9d2071 (available up to March 1st)

The link to yours is down.

**Comment by bratkrk** [comment]
I try many ways on many different computers and I don't know what happened but its working right now ;DDDDDD.

But I can give little advice:
-Don't import model from usb card, first copy to hard drive then import,
-If don't working copy model to system drive C;/ also MapsModelsImporter and try again,
-Download last blender I used this 2,82 final but it was unstable "like beta" but after few days they put new one, reinstall and it could change something.

Thanks a lot its unlivable!!!

**Comment by bratkrk** [comment]
Hi

Thanks a lot for Your help.
Your model also didn't working for Me but after few days of trying
reinstalling, trying on different computers... just start working.
I can't explain that !

Matt

niedz., 23 lut 2020 o 08:49 Elie Michel <notifications@github.com>
napisał(a):

**Comment by mowerybc** [comment]
I'm having a similar issue importing any .rdc. I've tried with the LaCorgne.rdc, capture.rdc and my own export from RenderDoc. Nothing happens in Blender (2.82.7) and the log doesn't show any prompt either. It does create a folder in the same path as the .rdc, with an appended 7-digit alphanumeric series (eg: LaCorogne-db5soat), but the folder is empty and a new one is created each time I try to import into Blender. I have a GeForce RTX 2070.

**Comment by mowerybc** [comment]
I'm having a similar issue importing any .rdc. I've tried with the LaCorgne.rdc, capture.rdc and my own export from RenderDoc. Nothing happens in Blender (2.82.7) and the log doesn't show any prompt either. It does create a folder in the same path as the .rdc, with an appended 7-digit alphanumeric series (eg: LaCorogne-db5soat), but the folder is empty and a new one is created each time I try to import into Blender. I have a GeForce RTX 2070.

**Comment by bratkrk** [comment]
I have one more idea let's turn off internet your firewall and antivirus
and try it again. I don't know why but it's couldl to be connected with
firewall.

czw., 27 lut 2020, 15:59 użytkownik mowerybc <notifications@github.com>
napisał:

**Comment by mowerybc** [comment]
Thanks for the suggestion, Matt. Sadly that didn't seem to do the trick.

**Comment by eliemichel** [comment]
@bratkrk I doupt this has anything to do with firewall. Working on USB stick might be a problem if it's running out of room because importing the rdc generate a lot of file, but nothing requires the C:/ drive afaik. Using last version of Blender (official release) is indeed mandatory.

@mowerybc There must be some log if it fails at that stage, see Windows > Toggle System Console. My bet is that you are not using the last version of the add-on. Please check that before reporting anything else...

**Comment by mowerybc** [comment]
You were correct; I had an older version of the add-on. I was also looking at the log window, not the console. 

I was able to get the LaCologne.rdc to work.
