### ISSUE TITLE
Inject into Process no longer an option in RenderDoc

### ISSUE THREAD

**Issue by ajccodes** [eliemichel/MapsModelsImporter#283]
In RenderDoc 1.25 I do not have the option to inject into process. Are there updated instructions to launch the chrome window from RenderDoc?

Thanks!

**Comment by EnamoredZeal** [comment]
It's under Tools then select  settings. Then look down to check the box to enable it.

**Comment by GeneralProtectionFault** [comment]
@EnamoredZeal  Thanks that was tripping me up too, even though I read elsewhere that it's an opt-in, I was looking for it in the installation options.  I think it'd be good if this made it into the Readme :)
