### ISSUE TITLE
Can't use the last release of RenderDoc with the last release of Chrome

### ISSUE THREAD

**Issue by Spirou4D** [eliemichel/MapsModelsImporter#291]
Chrome est à jour
Version 115.0.5790.110 (Build officiel) (64 bits)
RenderDoc
version 1.27 build 35b13a8e

When I run my favori with 
C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog"

Chrome open a popup with the gpu pid but I choose the pid and inject it in RenderDoc, and click the press button, Chrome create a  new pid popup etc..... 3x times !
And each time I don't see the pid in preview and can't capture it!

I have a MSI GTX1080Ti GPU and an Intel i9 last generation motherboard.

**Comment by Spirou4D** [comment]
Ok I hadn 't seen the release of RenderDoc : v1.13 only!!!!
Thks

**Comment by eliemichel** [comment]
For the record the version of RenderDoc that should be used with the last version of the add-on is 1.25, as specified in the [release notes](https://github.com/eliemichel/MapsModelsImporter/releases)!
