### ISSUE TITLE
why can't I import a rdc file?

### ISSUE THREAD

**Issue by lzy199qwe** [eliemichel/MapsModelsImporter#292]
blender 3.4
renderdoc 1.25
windows10

when import rdc file report this:

<img width="657" alt="捕获" src="https://github.com/eliemichel/MapsModelsImporter/assets/35828422/fdd04b02-b397-4fd5-b278-b98e16f3dfb8">

rdc file is:
[dijingfeng.zip](https://github.com/eliemichel/MapsModelsImporter/files/12214720/dijingfeng.zip)

**Comment by blacktion** [comment]
I met the same question, and i solved it by changing the language.(I changed it from Chinese to English and it worked.)
What's more, make sure your rdc file has 3D info.

**Comment by blacktion** [comment]
@lzy199qwe 
I met the same question, and i solved it by changing the language.(I changed it from Chinese to English and it worked.)
What's more, make sure your rdc file has 3D info.

**Comment by eliemichel** [comment]
I added a note about this in the readme, thanks for reporting!
