### ISSUE TITLE
RenderDoc1.6 won't capture

### ISSUE THREAD

**Issue by MaJeGHub** [eliemichel/MapsModelsImporter#32]
Hi Michel,
first of all I want to thank you for such excelent piece of work.
One month ago a achive this with Renderdoc1.2 and Blender 2.81

![image](https://user-images.githubusercontent.com/28965233/75122328-9735e500-569c-11ea-96e0-2aadbea9392f.png)

today I have tried to extend map with new models and I upgraded Blender and Renderdoc according to your description.
Google chrome 80, with new flag, Google maps, globe mode activated
 First of all renderdoc wont capture, I have noticed that OPENGLES was changed for D11, is that correct?
![image](https://user-images.githubusercontent.com/28965233/75122271-30b0c700-569c-11ea-840c-4b55a6755061.png)
Second, blender shows only this error:
![image](https://user-images.githubusercontent.com/28965233/75122456-f5af9300-569d-11ea-9a90-db8b5ec94eb2.png)

I tried MMI 0.2.0 rc3 and rc4 addon in blender2.82  but with same result. I used previous RDC file resaved with renderdoc 1.6

Is there anything changed to the workflow?
Thank you for your response in advance.
Mark

**Comment by MaJeGHub** [comment]
So I give it one more try and Renderdoc captured four pictures and no more.
![image](https://user-images.githubusercontent.com/28965233/75122645-21337d00-56a0-11ea-9bad-7d8e481ed812.png)
...and Blender successfuly convert low res model
![image](https://user-images.githubusercontent.com/28965233/75122662-54760c00-56a0-11ea-856a-ede8bd3ca99a.png)
but after that no capture in renderdoc again

Should I avoid something in renderdoc capture workflow?
I play around with it last four hours with same results. Sometimes it wont capture anything.

**Comment by eliemichel** [comment]
The switch from OpenGLES to D3D11 is intentionnal, indeed.

The "four pictures" are actually four captures, you can double click on them to browse their content.

If one of them is not importing correctly in Blender, please share here the .rdc file.

**Comment by MaJeGHub** [comment]
Hi,
 thanks for fast reply.
Yes it is captures not pictures :-), but my problem is that with previous version of RenderDoc I was able to capture on every single click on prtscr (infinite amount if i wish).
Now, with renderdoc1.6  it doesnt work(in most caseses) or alow me to capture only small amount of captures (1 to 4, than doesnt work again) I restart both instances of Google chrome and RenderDoc and try it again
Map import plugin to blender works well.

My question is if there is something I should do or avoid during google maps capturing.

Thanks in advance  
Mark

**Comment by eliemichel** [comment]
What do you mean by "it doesn't work", what is the exact symptom? Maybe record a video demonstrating the issue.

**Comment by MaJeGHub** [comment]
Hi, here it is...
symptom is that after pressing PrtScr renderdoc  is not capturing...
first part is wokflow with renderdoc1.2, second part is with 1.6 version

https://youtu.be/nIVF5_Q2uR0

**Comment by flxpx** [comment]
You could use the ‘Capture after delay’ Button as replacement for the Print Screen Key. It isn’t as convenient but it works ;)

Set it to after 5 seconds or so and switch back to chrome and pan around.

**Comment by MaJeGHub** [comment]
Ok, I will try it and then I post results. Thx for tip
