### ISSUE TITLE
Can't import any RDC file into Blender 4.1

### ISSUE THREAD

**Issue by SpanishNewbie** [eliemichel/MapsModelsImporter#327]
When I import the .rdc file in Blender, it only shows a tangled and untextured mesh. I already tried several .rdc files.
![malla informe](https://github.com/user-attachments/assets/b56248d0-6df2-4054-a1ef-49b0340e32c6)

 - 4 rdc files: https://file.io/844UKsbEU2Tc
 - Nvidia GeForceRTX 1050 Ti
 - MapsModelsImporter 0.7.0
 - Renderdoc 1.31
 - Blender 4.1
![error](https://github.com/user-attachments/assets/a816e379-2ae0-487e-8745-35cf9388388e)

Same thing happens with the samples.

**Comment by Sennodipoi** [comment]
Hello, I have this exact problem. I have an RTX 4070 though.
Did you manage to figure this out?

**Comment by SpanishNewbie** [comment]
> Hello, I have this exact problem. I have an RTX 4070 though. Did you manage to figure this out?

Yes. It was really simple. In Blender, go to Edit>preferences and change the language to english. That's it.
