### ISSUE TITLE
blender doesn't want to install addon...

### ISSUE THREAD

**Issue by sqr1be** [eliemichel/MapsModelsImporter#33]
[edit]
i downloaded from git hub (donwload zip button) DO NOT DO THIS... use the 'release' zip insteald (MapsModelsImporter-v0.2.0-rc4 or something like that.) after i downloaded the right zip the add on installed just fine) i'm only leaving this here in case someone else makes the same mistake
[/edit]

when i go to import the add-on via zip flie, i get told in the log that it installs, but no actual installation seems to occur.

Modules Installed () from 'C:\\Users\xxxxxxxe\\Downloads\\MapsModelsImporter-master.zip' into 'C:\\Users\\xxxxxxe\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons'

**Comment by eliemichel** [comment]
I added a note in README in f672065
