### ISSUE TITLE
nothing appering in blender when importing rdc files pls help me

### ISSUE THREAD

**Issue by bashar5252** [eliemichel/MapsModelsImporter#35]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - unable to put it
 - 0.13
- latest
 -2.82
pls help this is for my school

**Comment by eliemichel** [comment]
All right, it's good that you use the issue template, but please take some time making your message readable and feel like you spent more than 10 minutes trying.

You are using an outdated version of this add-on. Last version is 0.2.0, see the [releases section](https://github.com/eliemichel/MapsModelsImporter/releases).
