### ISSUE TITLE
RenderDoc API stays to "None"

### ISSUE THREAD

**Issue by frodooon** [eliemichel/MapsModelsImporter#38]
Hello,

First of all: this looks awesome, thanks! :smile: 
My problem is the following: when I click "Inject" for the "Google Chrome Gpu" thread, then I close the popup with the guid, I see my chrome page with the top message "You are using an unsupported command-line flag: ...", **but I don't see the black banner** with "OpenGLES. F12, PrtScrn to capture. ...". And in RenderDoc, the "API" flag remains to "None".

I use the latest Chrome version (as of yesterday), RenderDoc1.6, (and blender 2.82, but I'm not there yet), on Windows 10 (but this is a virtual Windows machine running on Centos8, I don't know if that can have an impact..).

Up to the injection process, the only difference I see with your video is that **I have only one popup that appears** with the Chrome guid, when you have 2 popups, with 2 guids..

If you have any idea on how to solve this, I'd appreciate a lot ;)

Arnaud

**Comment by frodooon** [comment]
Actually I don't understand: in the troubleshooting, it says:

**API: OpenGL (Not Presenting)**

_This was a common issue with versions of this add-on prior to v0.2.0. Update to the latest version of this add-on, then make sure you remove the --use-angle=gl option from the chrome shortcut._

..but this addon is only used by blender, _after_ the RenderDoc step, right? So how can this addon's version have an impact on RenderDoc's behavior?

**Comment by eliemichel** [comment]
Hi @frodooon 
First of all, as [noted in the troubleshooting section](https://github.com/eliemichel/MapsModelsImporter#chrome-is-showing-a-warning-about-an-unsupported-feature), the flag warnign should not be the source of the issue.

The number of popup should not affect, and it is more common to have only one, I believe the second ones pops up if it takes too much time to validate the first one.

Indeed Blender is not used at this stage, but the version number also refers to the instructions, that were different back before v0.2.0. In particular, the custom shortcut used to start chrome.exe was different and now it should not run on OpenGL but rather on DirectX. Which might be where your virtual machine setup fails, maybe. Are you able to run DirectX based application? I would be surprised if not, though, but check just in case.

**Comment by frodooon** [comment]
Hi,

I have DirectX12 installed, and I ran the diagnostic tool, below is what I see in the "Display" section, does it seem okay (I have no idea of what I'm looking at)..?

![image](https://user-images.githubusercontent.com/32676510/76638073-23288780-654c-11ea-82c2-09c57bd73d14.png)

For the remaining, I used the v0.2.0 instructions you gave.
Thanks if you have any idea to solve this...!
Arnaud.

**Comment by eliemichel** [comment]
Mmh idk, maybe screen record the process, as of now I don't see what could be wrong.

**Comment by Mastersquishy23** [comment]
I'm having the a similar problem... i do everything correct, the PID shows up and everything, but RenderDoc says API: None, and the "Capture Frame(s) Immediately" is grayed out... Any help would be greatly appreciated.

**Comment by eliemichel** [comment]
@Mastersquishy23 Same issue, same answer, at this point if you don't screen record your attempt I don't know how to help, this is a bug I cannot reproduce myself.

**Comment by Mastersquishy23** [comment]
Here you go: https://www.youtube.com/watch?v=0C8PHXhKe5k&feature=youtu.be
hopefully i wasn't too fast, if i was i will do it again slower, but you get the picture... 
Thanks again for taking time out of your day to help me. :)

**Comment by eliemichel** [comment]
The way you kill chrome at first is a bit violent ^^ Have you tried from a fresh start, without having started chrome yet?

**Comment by Mastersquishy23** [comment]
lol sorry about being violent, the renderdoc was making me angry lol. And no i haven't i'll give it a go. however i have uninstalled chrome, but i did start it up to check what the code line was again so i will restart and do it straight away.

**Comment by Mastersquishy23** [comment]
Yep i tried it again and still nothing, Chrome was literally the first thing i opened. :(. i might try again later, it might fix itself. Thanks anyway

**Comment by polygonfuture** [comment]
I have the same problem as others.  With using your shortcut I am never able to get the API status to change from 'None'.

**Comment by polygonfuture** [comment]
@eliemichel, Have you tried using with the absolute latest version of chrome?   What GPU are you using?     What driver version are your GPU?

**Comment by polygonfuture** [comment]
@frodooon @Mastersquishy23  In case neither of you figured it out, you must specfiically find the GPU process, not the browser process itself.   Make sure you are finding and selecting the specific PID that is listed in the GPU pop-up.

Hope this helps.

Cheers,
Jonathan

**Comment by eliemichel** [comment]
@polygonfuture Thanks a lot for identifying this issue, I just added an illustration in README. You can also check out the video instruction (though a bit old, there are some difference, in particular now it connects to D3D11 API rather than OpenGLES): https://www.youtube.com/watch?v=X6Q7dbtXVZQ

But in @Mastersquishy23 's case it was not the issue, on the video they inject into the right process.

**Comment by frodooon** [comment]
Hello, thanks @polygonfuture and @eliemichel for following this. Myself I was also already injecting into the GPU process, so that's not the solution for me.
Had it working on another computer though..

**Comment by kokitojj** [comment]
I followed all the steps but I still have the same problem. Thanks

**Comment by kokitojj** [comment]
> Here you go: https://www.youtube.com/watch?v=0C8PHXhKe5k&feature=youtu.be
> hopefully i wasn't too fast, if i was i will do it again slower, but you get the picture...
> Thanks again for taking time out of your day to help me. :)

the same . do you know how can I fix it?
thx

**Comment by eliemichel** [comment]
you can try using microsoft edge, with the same kind of custom shortcut (edge is basically a chromium with a slightly different ui)

**Comment by 01stefano** [comment]
hi, i also have the same problem, i tried 5 different versions of render doc but all with negative results, i'm on windows 8.1 amd hd 7600m graphics card if you can help me solve the problem i would be grateful.. tnx

**Comment by pichikaudaykiran** [comment]
Hi, I have the similar problem where API : None is showing in the status. I tried launching the weston application, it got launched successfully, but No frames are getting captured.
Is this is the problem because of **API : None** ?  
If so, can you please help me how to resolve this issue ?

**Comment by eliemichel** [comment]
Hi @pichikaudaykiran, sounds like you are trying to reproduce this on linux. The problem is that RenderDoc for linux is missing the Inject into process feature as far as I know. Did it change lately? Otherwise I am not aware of a workflow that enables the use of RenderDoc together with a web browser on linux unfortunately.

**Comment by jgarry90** [comment]
Same problem here. I am sure I selected the GPU process (the one mentioned in the startup dialog).
(updated windows10, chrome and edge tried, tried after rebooting also)

Any other hint?

**Comment by jgarry90** [comment]
Nevermind, I have very old graphics card (HD 6800) and even google maps 4d wont work (Google Earth yes, but I assume that it does by different means). DirectX12 is up and working, though

**Comment by eliemichel** [comment]
If https://earth.google.com/web/ works for you you can capture from it.

**Comment by aliamini87** [comment]
Hi
I had this issue and I found that none of the above issues were cause of the problem.
In my case the problem was the fact that I press the ok button of gpu id dialog before pressing the inject button in the RenderDoc. In this case, always "No API" appeared in the RenderDoc status.
Instead In the last time, after pressing the shortcut of the google chrome, I find the gpu pid and without clicking the "ok" button, found the process in the renderdoc and inject to it. After that i press the ok button of the gpu-pid pop-up and then chose my chrome user, after that when I looked at RenderDoc, the status of the  API changed to other thing.

**Comment by Ynaught** [comment]
I am trying to make this work for Microsoft Edge. No API shows up, when I click the "ok" button, it's no longer injected and it brings me back to the tab where I have to choose process to inject into. Clicking OK clears it from it being usable by RenderDoc but not clicking it means no API.

**Comment by bootygherk** [comment]
Had same problem , was using higher version of renderdoc.

Use RenderDoc 1.25: https://renderdoc.org/builds

it worked API D3D11 active and capture frame is not greyed out.

Hopefully the next parts will go smoothly.

**Comment by rodolforubens** [comment]
> Hi I had this issue and I found that none of the above issues were cause of the problem. In my case the problem was the fact that I press the ok button of gpu id dialog before pressing the inject button in the RenderDoc. In this case, always "No API" appeared in the RenderDoc status. Instead In the last time, after pressing the shortcut of the google chrome, I find the gpu pid and without clicking the "ok" button, found the process in the renderdoc and inject to it. After that i press the ok button of the gpu-pid pop-up and then chose my chrome user, after that when I looked at RenderDoc, the status of the API changed to other thing.

Thanks, that did it for me, needed to inject before pressing ok.
