### ISSUE TITLE
Import RDC fails - can't find texture file

### ISSUE THREAD

**Issue by atribolini** [eliemichel/MapsModelsImporter#42]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file
https://drive.google.com/file/d/1WGFYVPyiDz4I8gtXVZolLdTspDD6ghXp/view?usp=sharing
 - Your GPU name: Nvidia GTX 1080 - Studio Driver V 442.19
 - Version of this add-on (must be the most recent one) 0.2.1
 - Version of RenderDoc (1.6 recommended) v1.7
 - Version of Blender (2.82 recommended) 2.82 as well as 2.83 Alpha 2020-03-15

**Comment by eliemichel** [comment]
Do the texture also look like this when you inspect the rdc file in RenderDoc? I think I'm gonna use it to do some glitch art. ^^ Is it the only capture with which it does that? It is is not the only one, can you try RenderDoc 1.6 ? I haven't tried 1.7 yet (it's been out for only a week or so).

![renderglitch](https://user-images.githubusercontent.com/5802849/76913391-265aa500-68b7-11ea-9ac0-a4c10e687474.png)

**Comment by atribolini** [comment]
![image](https://user-images.githubusercontent.com/62003906/76925324-4e85dc00-6896-11ea-81ea-a3f67fb1adcc.png)

this is from the rdc I sent you. I tried renderdoc 1.6 and got the same error - texture.png missing.
I'm going to change the nvidia driver to the game ready version and try it again

**Comment by eliemichel** [comment]
Does the scene look like this in chrome when you attach RenderDoc, or is this only in the capture? Feels like a bug of RenderDoc itself, but if we were to report it it should be on another software because RenderDoc's developper clearly stated that he is against this use of his piece of software.

Do you have some similar behaviro if you try to capture a frame of some open source software using 3D like, e.g. Blender?

**Comment by atribolini** [comment]
that image is from RDC texture viewer. In chrome it looks like the thumbnail:
![thumb](https://user-images.githubusercontent.com/62003906/77019439-bd6a4000-693d-11ea-9399-7cdb55589a86.png)
I'm moving on to another project - thanks for engaging on this and your work on the add-in! Stay safe and healthy.
