### ISSUE TITLE
Only the Lite Mode of the new Google Maps is available at this time

### ISSUE THREAD

**Issue by albrrt** [eliemichel/MapsModelsImporter#43]
Hi,

This project looks very interesting, thank you for sharing!

This might be related to issue #38 

When opening Chrome normally, I see the 3D globe button and I can look around 3D models of buildings. 

I added the updated line you are mentioning in your video description:
`C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog" `
to the target field of the Chrome shortcut.

When I double-click on the shortcut, I have 4 GPU popups appearing one after another and I have to re-inject the process in Renderdocs 4 times (Refresh > Select new process > Inject).

After injecting a process, the Renderdoc API shows : **D3D11 (Active)**  for a short period of time before a new Chrome process popups. After injecting the last process, the API shows: None.

Then, I navigate to Google Maps on Satellite view but the 3D Globe button doesn't show.
I tried appending `?force=webgl` at the end of the url but I get a message saying

> We're sorry, only the Lite version of the new Google Maps is available at this time

I can usually run DirectX applications like video games.

I am using 
- RenderDoc 1.6
- Windows 10 Version 10.0.18362 Build 18362 (latest)
- Chrome 80.0.3987.149 (Official Build) (64-bit) (latest)
- NVIDIA GTX 960M

Note: It seems to have messed up with my GPU or driver somehow as I can't open any game anymore, and none of my Adobe CC programs - they all crash at startup - unless I disable my NVIDIA GTX 960M device in Device Manager. I had to do a system recovery.

Is there a way to solve this?

Thank you for your help

**Comment by eliemichel** [comment]
Hi @albrrt thanks for this detailed bug report, you seem to have invested a fair amount of effort in this! First of all, if it is this process that messed up with your GPU, my apologies (even though I don't take responsibility as stated in the licence), you'd be the first to report such problem.

Then, if you can disable the GTX 960M, does it mean you have another graphics device, say you're on a laptop with an integrated chip? If so, you may try with it, people reported the process to work even on such low end hardware.

Also, as soon as the API is set to "None" in RenderDoc, you have no hope of capturing anything, it is at this stage that there is something to work out. Once again, if you have several graphic devices, you can right click on the shortcut and chose which one to run the app with.

**Comment by albrrt** [comment]
Thank you for your answer.

Yes I do. I tried disabling my GTX 960M and run the programs with my Intel(R) HD Graphics 530, but unfortunately I'm experiencing the same issues.

The API displays "None" after the fourth popup and I my DirectX apps crash if I re-enable my GTX 960M back.

> if you have several graphic devices, you can right click on the shortcut and chose which one to run the app with

I couldn't find this option in the shortcut properties, but I set Google Chrome to run on Integrated Graphics processor in my Nvidia's Control Panel.

I'm not an expert in hardware. Maybe I am doing something wrong or this issue is specific to my laptop or my graphics card. I will try on a desktop PC when I have access to one and let you know.

**Comment by albrrt** [comment]
Hi @eliemichel I tried on a desktop PC with a single GPU and it worked like a charm.

So this issue is probably specific to my laptop or to laptops with 2 graphic devices.

Thank you very much for your replies!

**Comment by eliemichel** [comment]
For the record I tried with a laptop with 2 graphic devices and it worked, so it must be more specific to your setup! Thanks for the feedback.

**Comment by ILikeTrains27** [comment]
I'm getting the same issue, for some reason it opens a window saying "Gpu starting with pid" 4 times instead of just one, and when I try to inject into the last one, it doesn't work. I only have 1 GPU too. However the 3d globe on google maps works for me, although it didn't work at first so I had to reinstall chrome. Should I sent the RenderDoc log?

**Comment by ILikeTrains27** [comment]
Wait the 3d globe doesn't work anymore, when I go to chrome://gpu/ it says OpenGL: Disabled. Something that I noticed is that when I turn hardware acceleration off in chrome, then there is only 1 GPU popup, but chrome needs hardware acceleration for 3d rendering.
