### ISSUE TITLE
Captured Empty glDrawElements

### ISSUE THREAD

**Issue by onuroztrk** [eliemichel/MapsModelsImporter#45]
Hi

I'm using portable chrome and RenderDoc 1.6 as you suggested because if i use normal chrome when i press printscreen pid dialog pops up again and google earth goes black. When i capture everything seems fine but it isn't. When i click the texture view it is all black and glDrawElements are empty but file is around 122 mb after saving. After importing .rdc in blender nothing happens.

![Capture1](https://user-images.githubusercontent.com/8490105/77298952-c459cf80-6cfc-11ea-8e86-39353fa1a596.JPG)
![Capture2](https://user-images.githubusercontent.com/8490105/77298958-c6239300-6cfc-11ea-9df9-256c9269eeda.JPG)

My .rdc file:
https://drive.google.com/open?id=1CztAjjgNTu1fSvAmxcGYLBQAarfnJTap

**Comment by eliemichel** [comment]
First things first: capture Google **Maps**, not Google Earth. I'll reopen if the issue still holds.
