### ISSUE TITLE
RDC import failed

### ISSUE THREAD

**Issue by Elijah-Neverdie** [eliemichel/MapsModelsImporter#51]
RDC import error
![Error](https://user-images.githubusercontent.com/20200023/79734789-dba2d180-8329-11ea-95d9-8a37a14cc075.png)

 - The .rdc file
 - Your GPU name: RTX2080
 - Version of this add-on (v0.2.0-rc4)
 - Version of RenderDoc (1.7)
 - Version of Blender (2.82)

**Comment by eliemichel** [comment]
Hi @Elijah-Neverdie,
You must switch your Blender to English. This is a known limitation of the add-on.
