### ISSUE TITLE
Cannot import into Blender either

### ISSUE THREAD

**Issue by shoqman** [eliemichel/MapsModelsImporter#55]
I am using a 2080ti
Addon .2.2
Renderdoc 1.6 Portable
Blender 2.82a
And here is the RDC file in question, as well as the console output:
https://www.dropbox.com/s/wkc6o7mgcnl2nzf/MapImporter.zip?dl=1

When I attempt to import a rdc file, i get this:

> Invalid RDC capture file. Please make sure that:
> 1. You are importing from Google Maps (NOT Google Earth)
> 2. You were MOVING in the 3D view while taking the capture (you can use the Capture after delay button in RenderDoc).
> Please report to MapsModelsImporter developers providing the .rdc file as well as the full console log.
> Console log is accessible in Windows > Toggle System Console (right click to copy).

And I am using the time delay, moving the mouse in 3d when it captures. Tried several frame consecutively as well to no avail.

**Comment by raftgs** [comment]
Hi @shoqman,

I've got the same issue. In fact what you need to do is to go inside Chrome just after clicking on 'Capture Frame Immediately'.

Best,
Raffaele

**Comment by shoqman** [comment]
Hi @raftgs ,
I have tried it that way as well, capture immediately, capture with delay etc, always in 3D mode and it always creates a file that cannot be imported into Blender, unfortunately.

**Comment by eliemichel** [comment]
HI @shoqman the bullet point 1. is the one you should look at: you are capturing from Google Earth while the add-on is for Google **Maps**.

**Comment by shoqman** [comment]
> HI @shoqman the bullet point 1. is the one you should look at: you are capturing from Google Earth while the add-on is for Google **Maps**.

Oh my, I don't know how I read that incorrectly. Many apologies, thanks!
