### ISSUE TITLE
How to export obj file after texture packer?

### ISSUE THREAD

**Issue by saedrna** [eliemichel/MapsModelsImporter#56]
Hi Elie,

I have bought the merger and packer and have successfully run the packer.
It packs all the UV charts into a single atlas. However, the mesh still has many materials and blender can not sucessfully export the obj file with texture. See screen shot below.

I attached the material file below. In fact, I am not quite familiar with blender and do not quite understand the pipeline to export the mesh.

Would you please kindly give me some specific instructions of exporting a textured obj file in Blender? 

Thanks,
Han
[ny.mtl.txt](https://github.com/eliemichel/MapsModelsImporter/files/4714606/ny.mtl.txt)
![scene](https://user-images.githubusercontent.com/3850191/83477607-3b160480-a4c6-11ea-9bff-988eac5755d5.png)
![uv_atlas](https://user-images.githubusercontent.com/3850191/83477610-3ea98b80-a4c6-11ea-8bec-fb1e7bb22672.png)

**Comment by eliemichel** [comment]
Hi @saedrna here is my workflow:

 - Merge
 - Pack
 - Apply the same material to all the selection using Ctrl+L > Material
 - Join all meshes (Ctrl+J), now thanks to the previous step there should be one single material
 - export as OBJ
 - If the mtl file does not link to the image like yours, you can simply put the image name after `map_Kd `. To save the image from Blender in the UV editor go to `Image > Save` menu.
