### ISSUE TITLE
local variable 'mdata' referenced before assignment

### ISSUE THREAD

**Issue by maifeeulasad** [eliemichel/MapsModelsImporter#58]
Here is the complete log : 
```
bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 1 object(s)
Modules Installed (MapsModelsImporter) from 'C:\\Users\\MUA\\OneDrive\\Documents\\MapsModelsImporter-v0.2.1.zip' into 'C:\\Users\\MUA\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons'
bpy.context.space_data.system_bookmarks_active = 1
Traceback (most recent call last):
  File "C:\Users\MUA\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    importCapture(context, self.filepath, self.max_blocks, pref)
  File "C:\Users\MUA\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 210, in importCapture
    filesToBlender(context, prefix, max_blocks)
  File "C:\Users\MUA\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 176, in filesToBlender
    uvOffsetScale, matrix, refMatrix = extractUniforms(constants, refMatrix)
  File "C:\Users\MUA\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 83, in extractUniforms
    mdata[0:4],
UnboundLocalError: local variable 'mdata' referenced before assignment

location: <unknown location>:-1
```
Blender : 2.82
**MapsModelsImporter:0.2.1**

**Comment by eliemichel** [comment]
Hello @maifeeulasad could you provide the rdc file please?

**Comment by maifeeulasad** [comment]
@eliemichel here are all three files, I have tried : https://drive.google.com/drive/folders/13TXmGRtulJk1PlHR3K0846wzR_eDuoKE?usp=sharing

**Comment by eliemichel** [comment]
The first capture is from Google Earth. The documentation as well as the error message itself are clear on this: the add-on is NOT for Google Earth, it is for Google Maps.

The second capture is from Google Maps, but without enabling 3D nor even satellite view. The add-on only capture what is visible in the browser, so if you don't see any 3D it won't capture any 3D.

The third capture is from Google Maps in the right mode, but you were not moving in the viewport while taking the capture.

I guess the fourth will be the right one. ;)

**Comment by maifeeulasad** [comment]
@eliemichel just to be sure, can you try to map nearby area of this coordinate : **22°28'15.6"N 91°47'06.0"E**. I'm not even sure, if this place contains 3D data or not. I'm just introduced to rdc capturing.

Here is the link : https://www.google.com.bd/maps/place/22%C2%B028'15.6%22N+91%C2%B047'06.0%22E/@22.4710193,91.7845788,383m/data=!3m1!1e3!4m13!1m6!3m5!1s0x30acd6fe9a3a4473:0x7836276aef538552!2sUniversity+of+Chittagong!8m2!3d22.4715718!4d91.7876793!3m5!1s0x0:0x0!7e2!8m2!3d22.4709968!4d91.7850078

It will be really helpful, thanks.
If it does please tell me what I was doing wrong and it will more nice if you just send me related files along that.

**Comment by eliemichel** [comment]
There is indeed no 3D data about the buildings in this area. The process should work anyway but it just grabs the mountains and textures in that case.

**Comment by maifeeulasad** [comment]
thanks a lot @eliemichel
