### ISSUE TITLE
Addon on Blender 2.80.74 ( Jun 2019 )

### ISSUE THREAD

**Issue by magadan** [eliemichel/MapsModelsImporter#6]
Hi, thanks for the tool !

Im getting no import results, with Blender 2.80.74 ( latest RC  jun/2019 )

Console Windows:
 
AttributeError: 'renderdoc.CaptureFile' object has no attribute 'shutdown'
Info: Deleted 1 object(s)

I can't find the same version (2.80.53) of your youtube video to try the addon again.

Any idea ?

**Comment by eliemichel** [comment]
Hi @magadan, thank you for your feedback. This is the error I get when using a too recent version of RenderDoc. Did you consider this part of the README?

> It has been reported not working with the very last version. Try the portable version of RenderDoc 1.2 or RenderDoc 1.1.

Which version of RenderDoc did you use to create the capture file?

**Comment by magadan** [comment]
Ok ! I downloaded the version 1.2 and im getting this error now:

File "C:\Users\mgd\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 41, in list_relevant_calls
    if _strategy == 0:
RecursionError: maximum recursion depth exceeded in comparison

obs: um using the latest version of your script 1.1.

**Comment by eliemichel** [comment]
Ah this problem had been solved, but after the 0.1.1, so I just released a 0.1.2 that should fix it:
https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.1.2

**Comment by magadan** [comment]
ok, now with the 0.1.2  running blender 2.80.74 (latest) i tried with different versions of RenderDoc.

WIth renderdoc 1.1 = Error: Could not find the beginning of the relevant 3D draw calls
With renderdoc 1.2  = Error: Could not find the beginning of the relevant 3D draw calls
With renderdoc 1.4 = AttributeError: 'renderdoc.CaptureFile' object has no attribute 'shutdown'

I change the map style on webpage to "Clean', without marks and etc.. I dont know if this has impact.

**Comment by magadan** [comment]
I you want to see my capture with RenderDOC 1.1  
here: https://drive.google.com/file/d/13_rFvpwz70z6o_y9fi43SlKxnlEr9kPA/view?usp=sharing

**Comment by magadan** [comment]
Hey, i found the bug !

The bug is, im going to the Google Earth URL instead of Google Maps URL !

Now its all working ! Thank you !

**Comment by eliemichel** [comment]
Ok good, I added a note about this in the README to prevent future users to run into similar confusion! ;)

**Comment by RutgerRauws** [comment]
Hi Elie!

First of all, thank you for making this great tool! Very excited to use it!
I am still experiencing this issue on release version 0.1.2 using Blender 2.80.75. I have also tried using release version 0.1.1, but this threw the same error.

I can't seem to downgrade to Blender 2.80.74. Could you have a look? I am getting this error on my own capture, but also on the [capture](https://blog.exppad.com/public/webgl-renderdoc/gmaps/capture.rdc) provided by you in the article [Importing Actual 3D Models From Google Maps
](https://blog.exppad.com/article/importing-actual-3d-models-from-google-maps). 

Here's the full log:
``` 
PS C:\Program Files\Blender Foundation\Blender> ./blender.exe -d
Switching to fully guarded memory allocator.
Blender 2.80 (sub 75)
Build: 2019-07-29 09:44 AM Windows
argv[0] = C:\Program Files\Blender Foundation\Blender\blender.exe
argv[1] = -d
Read prefs: \\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
read file
  Version 280 sub 39 date unknown hash unknown
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender\2.80\python
Info: Deleted 3 object(s)

addon_utils.disable: MapsModelsImporter not loaded
addon_utils.disable: MapsModelsImporter not loaded
Modules Installed (MapsModelsImporter) from '..\\MapsModelsImporter-v0.1.2.zip' into '\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
module changed on disk: '\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons\\MapsModelsImporter\\__init__.py' reloading...
Loading capture from capture.rdc...
Couldn't initialise replay: 14
Traceback (most recent call last):
  File "\\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MapsModelsImporter\google_maps_rd.py", line 170, in <module>
    with CaptureWrapper(CAPTURE_FILE) as controller:
  File "\\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MapsModelsImporter\rdutils.py", line 49, in __enter__
    self.cap.shutdown()
AttributeError: 'renderdoc.CaptureFile' object has no attribute 'shutdown'
``` 

Thanks in advance, and thanks again for making this plugin!
Rutger

**Comment by eliemichel** [comment]
Hi Rutger,
It's interesting to see it does not work with the capture file I provided. It must be that the capture file somehow depends on the architecture of the GPU or something. What GPU do you have? If you are using a laptop, did you ensure it runs on the actual GPU and not the integrated chip?
