### ISSUE TITLE
[Question] How to match tiles with coordinates?

### ISSUE THREAD

**Issue by mwussow** [eliemichel/MapsModelsImporter#62]
Dear Elie,

thanks for this amazing tool!
I have been using it for a while to collect data for 3D deep learning experiments. One thing I am struggling with are the different scales of the tiles and the lack of coordinates. By any chance, do you know of a way to map coordinates (e.g., lat/long) to the exported meshes or about an automatic way to align the scale of many individual tiles that are not adjacent (I already know of LillyTexturePacker)?

Looking forward to hear from you!

Thanks in advance,
Moritz

**Comment by eliemichel** [comment]
Hi Moritz,

Extracting a lat/long coordinate from captures is something I've been asked a lot, and so I tried but the main issue is that it is likely that this information is not embedded at all in the capture. The process captures what is sent to the GPU, hence what is needed for rendering, and the geographic location is not exactly needed for this.

If you want to align the tiles issues from several overlapping captures, you can try this other tool, LilyCaptureMerger: https://gumroad.com/l/KSvXuu It relies on textures to find matching tiles between two captures and transform all the tiles from one capture to match the other one.

Demo: https://youtu.be/BcGM76dwF_s

**Comment by mwussow** [comment]
Thanks for your prompt reply! I guess the only way to map coordinates would then be by identifying 3 known coordinates on the tile and perform some sort of triangulation.
