### ISSUE TITLE
Another Cannot Import RDC file....

### ISSUE THREAD

**Issue by Enon813** [eliemichel/MapsModelsImporter#63]
Hello, I don't know how many times I can say that I try to import an RDC file, and I followed several tutorials and also that of the author and none of them have worked, none of them matter or try 3D or 2D mode, but the strange thing is that when I take a capture it doesn't Unless it enters the chrome process, that is, when I click on the google maps page if it captures, perhaps that is why but I do not see another way of seeing how to take the capture correctly, even sometimes I feel that it can no longer be done. that and tried all the forms and even with the recommended versions of Renderdoc 1.6 and 1.7 also of blender and even versions of the add-on and nothing works will the gpu be?

 - The rdc file

 - Ryzen 2200g igpu 
 - Version of this add-on 0.2.2
 - Version of RenderDoc (1.8v
 - Version of Blender (2.82

![Error](https://user-images.githubusercontent.com/34198168/85231462-c3e4d980-b3bc-11ea-8042-a09beb436611.png)

**Comment by eliemichel** [comment]
Could you provide the rdc file that fails at being imported?

**Comment by JINI-JINI-CSJ** [comment]
I have the same problem.
0.2.2 mapimport
blender 2.83
renderdoc 1.8

![2020-06-22-2](https://user-images.githubusercontent.com/67236374/85232274-b9682580-b438-11ea-9d2b-4a958cb8c973.png)
![2020-06-22-1](https://user-images.githubusercontent.com/67236374/85232279-be2cd980-b438-11ea-9212-cb2f03a1b8a3.png)

**Comment by eliemichel** [comment]
@JINI-JINI-CSJ It's very likely that you were not moving in the viewport while capturing the rdc file. Maybe try the "Capture after delay" button. Also, you might have to turn your UI to English for importing captures in Blender, sorry for that.

Once again, I cannot tell much without getting the actual rdc file that you are trying to import...

**Comment by JINI-JINI-CSJ** [comment]
https://drive.google.com/file/d/14BWehMcpAiiExXQq6hjIEbMRUb6QGwfN/view?usp=sharing

Is there an error in this file?
I would appreciate it if you check it out.

**Comment by eliemichel** [comment]
This is a capture of Google Earth. If you read the error message on the screenshot you reported it says "do NOT use Google Earth, use Google Maps instead".

**Comment by Enon813** [comment]
After watching several videos, some showed using the delay capture while activating the delay, move the google maps and when the capture is finished it is resolved

**Comment by Enon813** [comment]
> I have the same problem.
> 0.2.2 mapimport
> blender 2.83
> renderdoc 1.8
> 
> ![2020-06-22-2](https://user-images.githubusercontent.com/67236374/85232274-b9682580-b438-11ea-9d2b-4a958cb8c973.png)
> ![2020-06-22-1](https://user-images.githubusercontent.com/67236374/85232279-be2cd980-b438-11ea-9212-cb2f03a1b8a3.png)

After watching several videos, some showed using the delay capture while activating the delay, move the google maps and when the capture is finished it is resolved

**Comment by eliemichel** [comment]
You are still using Google Earth. This add-on is for Google Maps, which is **a different website**: http://maps.google.com/maps
