### ISSUE TITLE
Importing messed up capture in Blender

### ISSUE THREAD

**Issue by ludoviz** [eliemichel/MapsModelsImporter#64]
Hi everybody. I'm trying to import the capture into blender but what I get is a messed up collection of surfaces. Any idea on how to solve this? 
![image](https://user-images.githubusercontent.com/51930689/86012686-89afb380-ba1e-11ea-8223-539b133a8fc2.png)
I used :
- mapsModelImporter v.0.1.3
-renderdoc v1.2
-blender v.2.83
-vivaldi as browser for google maps

I provide a link to the capture file here [https://www.dropbox.com/s/eqiai0aymzyg6ec/capture_weird.zip?dl=0](url)

Thanks for any help!

**Comment by eliemichel** [comment]
Any reason why you are using this version of the add-on? The new recommandation is to use last version of Chrome and RenderDoc, together with the last version of the addon.

**Comment by ludoviz** [comment]
yep ... I had other issues with the most recent version, previously for me was impossibile to import in blender at all (giving me a "file not found" error), then I read another post here, where a guy was advised to try an older version of the add-on (to use openGL instead of directx) ... I frankly doubt our problem was the same, but I gave a try and at least I got somehing inside blender. 
I'll try again with the 0.2.2 version and let you know.
