### ISSUE TITLE
Gaps in RDC File in Blender

### ISSUE THREAD

**Issue by Abbe-Engers** [eliemichel/MapsModelsImporter#65]
![Schermopname (176)](https://user-images.githubusercontent.com/31761483/86173103-bc8da080-bb1f-11ea-9371-619f2b337031.png)

As you can see I have some corner gaps between tiles and I don't know how I could fix it.

I run on an GTX 1060 6GB
- latest version of renderdoc
- Blender version 2.82
- most recent version of your add-on

**Comment by eliemichel** [comment]
I noticed this too. It may be that those small triangles are added during an extra call. Would you be able to find when browsing the capture in renderdoc the very drawcall that should contain the triangles that are missing upon import?

**Comment by Abbe-Engers** [comment]
I don't have much experience in renderdoc so I don't know what you mean with the drawcall but I've found that the textures of the triangles are loaded and in blender you can simply go into edit mode and fix and it's as good as normal. 

I couldn't find any of the loose triangles if I scroll true colorpass 1 in the texture viewer so I think it's an import problem.

**Comment by Nyco3d** [comment]
Hi,

I have the same bug, using the latest recommended versions (render doc 1.10, blender 2.91, and MapsModelsImporter-v0.3.5-rc2). It would be great if it could be fixed!
By the way, it's a great plugin! Thank you so much for it ! It allows me to continue a 3D project I do in my free time. 
Best regards,
Nicolas

**Comment by Nyco3d** [comment]
Hi Elie,

I found how to fix it. It's in the generation of triangles.
In the file google_maps.py, we have this line:
`tris = [ [ indices[i+j] for j in [[0,1,2],[0,2,1]][i%2] ] for i in range(n - 3)]`

When changing "n-3" by "n-2", all gaps are gone.

See the before/after comparison:
![maps_import_01_bug](https://user-images.githubusercontent.com/79358062/108643809-7620f380-74ac-11eb-9d95-9b7a5fc011ab.png)

![maps_import_02_fix](https://user-images.githubusercontent.com/79358062/108643817-86d16980-74ac-11eb-9ff7-07de46a2d536.png)

Best regards,
Nicolas

**Comment by beantowel** [comment]
this patch is not present in the latest release (v0.6.2)
