### ISSUE TITLE
[QUESTION] Execute Lily Capture Merger from Blender Script

### ISSUE THREAD

**Issue by Abbe-Engers** [eliemichel/MapsModelsImporter#68]
I’m stuck because I don’t know to run the Lily Capture Merger python file from a blender script. I successfully selected the two objects inside the two seperate collections that I’m trying to merge and I made one of them active so they know where to merge to but I couldn’t find any function name to execute it. 

Please let me know!

**Comment by eliemichel** [comment]
I recommend you enable the "Python Tooltip" in user preferences:
![](https://docs.blender.org/manual/en/latest/_images/editors_preferences_section_interface.png)

Then you'll see that you can trigger capture merger using `bpy.ops.object.lily_capture_merger()` ;) You can also use the [Info Editor](https://docs.blender.org/manual/en/latest/editors/info_editor.html).
