### ISSUE TITLE
Notable use cases link?

### ISSUE THREAD

**Issue by andybak** [eliemichel/MapsModelsImporter#70]
Would it be better to link to the artist's actual website instead of an Instagram post?

Something like https://benjaminbardou.com/megalopolis/mglp002

**Comment by eliemichel** [comment]
Hi Andy,
Most of the images at that address don't use MapsModelImporter, I've linked to the ones explicitely stating so to be sure not to abusively claim usage where it isn't actually used. But you're right about using the true website, I've just added a link (21a8a87) to their home page (and ftr I asked for consent before adding the instagram links!).
