### ISSUE TITLE
Google Maps OR Google Earth ?

### ISSUE THREAD

**Issue by U-DayBha** [eliemichel/MapsModelsImporter#73]
Hi MapsModelsImporter (the Team),

Greetings
As You suggested, I am sharing my error detail as follows with **.RDC** & **Word Doc** ( as I found it in Blender _ _Report to MMI ..._)
 

- [ ]  I got trouble in _Step 8_. **In Blender, go to File > Import > Google Maps Capture an choose your capture file**.

Till this step, everything is functional.
Usages Detail:    Blender : _v2.83._3    ;     Render Doc : _v1.9_    ;       MMI: v_0.3.0_    
Graphics Card : Nvidia Quadro P620 (2GB ram)    ;    Windows10     ;      Intel Core Duo 4GB ram

 

- [ ]  Now I tried to capture some other location, but failed??
What changes I need to do to Chrome?

 

- [ ]  For me to try in Google Earth, **_suggest Vividly_** (as earlier in Video) even in description _(or prescription 👍 )_

Thanks & Regards for your **Enthusiasm, Patience & Time**

[Trial Error - Aug2020.docx](https://github.com/eliemichel/MapsModelsImporter/files/5137319/Trial.Error.-.Aug2020.docx)

[2241 NBC.zip](https://github.com/eliemichel/MapsModelsImporter/files/5137337/2241.NBC.zip)

**Comment by eliemichel** [comment]
Hi @U-DayBha 
The problem with your capture is that you were not in 3D mode in maps when taking it!

**Comment by U-DayBha** [comment]
Alright, thank you very much.
I will check that 🙂
Regards
