### ISSUE TITLE
Cannot import RDC

### ISSUE THREAD

**Issue by bmalcherek** [eliemichel/MapsModelsImporter#77]
Hi, I'm trying to import .rdc file to blender, but I get the usual error notification

![obraz](https://user-images.githubusercontent.com/34577736/92325738-32951300-f04d-11ea-98d4-80709710bd78.png)

 - rdc file - https://drive.google.com/file/d/1hk0W2vWZWsQ0Il0TXKqU0fJh2Q3QMTaL/view?usp=sharing
 - GPU - RTX2060 SUPER
 - MapsModelImporter v0.3.1
 - Blender 2.82
 - RenderDoc 1.6

I'm using maps.google.com and capturing with option trigger after delay of 1 second (Capture Immediately also doesn't work) while moving the viewport. Blender console is clear. I'm starting Chrome with this command `"C:\Program Files\Google\Chrome\Application\chrome.exe" --disable-gpu-sandbox --gpu-startup-dialog`

**Comment by eliemichel** [comment]
Hi @lordmalcher I can import your capture file correctly:

![a1](https://user-images.githubusercontent.com/5802849/93015105-f7e42b00-f5b6-11ea-93d3-eea62f41fe44.png)

Can you turn extra debug info on in the addons preferences and report the full log from the terminal (Window > Toggle System Console, then use right click to copy content as text)

**Comment by laurent13009** [comment]
Hi, I'm getting the same error on blender 2.83.6.0

Invalid RDC capture file. Please make sure that:
1. You are importing from Google Maps (NOT Google Earth)
2. You were MOVING in the 3D view while taking the capture (you can use the Capture after delay button in RenderDoc).
Please report to MapsModelsImporter developers providing the .rdc file as well as the full console log.
Console log is accessible in Windows > Toggle System Console (right click to copy).

I've reverted to RenderDoc v1.9 but doesn't seem to fix it. It used to work so I probably changed something but can't figure out what...


Thanks for you help!


https://drive.google.com/file/d/1EX6P3eFlPB_hHQm5lJntNaCOfbpxeCeF/view?usp=sharing
[kona_aviation_services.log](https://github.com/eliemichel/MapsModelsImporter/files/5289291/kona_aviation_services.log)

**Comment by eliemichel** [comment]
The capture looks like you were not moving in the viewport while taking it!

**Comment by Ristophonics** [comment]
Getting the same error as well on what was previously working. I was able to open previously captured rdc in blender files as well. Only the latest captures are reporting an error in blender.
