### ISSUE TITLE
No 3d Info Captured by RenderDoc

### ISSUE THREAD

**Issue by Perpaterb** [eliemichel/MapsModelsImporter#79]
Hey Champ

![Capture](https://user-images.githubusercontent.com/22626962/93097432-e7cc6880-f6e8-11ea-894c-f3bf649e4655.PNG)

Have tried RD 1.9 and 1.6

C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog --use-angle=gl"

Also tried Vivaldi it was just black.

Reinstalled Chrome

[001.zip](https://github.com/eliemichel/MapsModelsImporter/files/5218938/001.zip)

P.s Even if you can't help me. You are a top notch bloke for making this a thing and the support you have given to loads and loads of people.

Thanks

Andrew

**Comment by Perpaterb** [comment]
Chrome Version 85.0.4183.102 (Official Build) (64-bit)

Opengl not presenting might be the problem

**Comment by eliemichel** [comment]
Were you moving in the viewport while taking the capture? (Using the "Trigger after delay" button for instance)

**Comment by Perpaterb** [comment]
Hi Elie 

I was moving.

Tried  "Trigger after delay"  same thing :( 

Thanks for your help.
[002.zip](https://github.com/eliemichel/MapsModelsImporter/files/5222362/002.zip)

**Comment by eliemichel** [comment]
Are you on a laptop with two GPUs? It seems that Chrome is using both OpenGL and DirectX and uses the latter only for presenting on screen while the actual 3D rendering is done with OpenGL. You could try capturing several consecutive frames by increasing the "Capture X Sequential frame(s)" to 2 or 3.

**Comment by Perpaterb** [comment]
Hi Elie

I have tried on 2 computer now.
First computer is a desktop with 1 1080ti (all posts before this one were using it)

Second A MSI 5YO gaming laptop. 

![laptop renderdov001](https://user-images.githubusercontent.com/22626962/93572098-b4cff080-f9d8-11ea-9480-d047cfca91bf.PNG)

Seems like almost the same result. 
Also tryed "Capture X Sequential frame(s)"

Is there some OpenGl APL or Visual studio something that I need to install?

[003.zip](https://github.com/eliemichel/MapsModelsImporter/files/5244193/003.zip)

Thanks

**Comment by eliemichel** [comment]
It is not supposed to even try to use OpenGL, it should be all running on D3D11. Are you sure you are running Chrome the correct custom shortcut? It should be:

```
C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog"
```

**Comment by Perpaterb** [comment]
I was using

 C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog --use-angle=gl"
Not
C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog"

Seems to work or at least capturing something.

Thanks man. 

![Capture](https://user-images.githubusercontent.com/22626962/93589180-cc66a380-f9ef-11ea-8226-f79bae42cec5.PNG)

I sware I tried without "--use-angle=gl" but I guess in all my failing to get the GPU pid popup I stuffed it up.

Thanks man

**Comment by eliemichel** [comment]
Thanks, I updated the youtube video description.
