### ISSUE TITLE
Parallels Desktop: No API Connection / Multiple Injections / 3D Earth View not available

### ISSUE THREAD

**Issue by julesfelix** [eliemichel/MapsModelsImporter#80]
Hi Élie,

I have a series of problems with the process.

To my setup:
- Parallels Desktop with Windows 10
- Google Chrome (latest Version) / Also tried Google Chrome Version 80
- Render Doc 1.9 / Also tried Render Doc 1.7 (As suggested in another inquiry)

To my problems:
- When trying to inject into google chrome, I always have to do it several times, in order for it to work (although the black bar on top of the browser doesn't show up...)
- When injected, API doesn't connect
- When in Google Maps: "3D Earth View not available" is stated at the lower bar

Do you have an idea why this might not work? Is it because of Parallels?
Thank you so much in advance - really appreciate the great support and all the stuff you're investing in updates and so on! 
I really need this to work for my master's thesis - hence the report...

All the best,

Julian

**Comment by julesfelix** [comment]
update: 

Connection of API worked by changing the Target to:

""C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --no-sandbox --disable-gpu-watchdog --gpu-startup-dialog --use-gl=desktop"

Nevertheless, 3d in Google Maps is still disabled...

**Comment by eliemichel** [comment]
Sounds like you followed outdated information, refer to the readme for up to date details, in particular the target of the shortcut must be:

```
C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog"
```

As a result of this, Chrome should be using D3D11, not OpenGL!

**Comment by julesfelix** [comment]
Thanks for the reply, yeah I followed the readme quite accurately, but since that didn't work, out of desperation I tried some other shortcuts...
I just tried it again, but still doesn't work. API stays "none" and once I'm in Chrome and go to maps, it switches to some kind of "google maps lite version" which doesn't support 3d
Do you think it could be because of parallels desktop, running windows 10 on Mac? (btw. I also checked DirectX and Windows, but both are up do date...)

**Comment by eliemichel** [comment]
Might well be because of parallel desktops, I have no way of checking myself, I don't have a mac :/

**Comment by julesfelix** [comment]
It worked! But only works with Parallels Desktop 15 and Blender 2.82.... 
I have a bit of another problem right now, LilyTexturePacker isn't working as it should. Maybe you know a solution to this error?

location: <unknown location>: -1

Value Error: could not broadcast input array from shape (255,54,4) into shape (222,54,4)
   packed_pixels [y:y+h, x:x+w, :] = pixels
 File (...), line 132 in pack_textures
 File (...), line 36 in execute
Traceback (most recent call last):

It appears when all meshes are selected and I'm running the command.
Thanks a lot!

**Comment by eliemichel** [comment]
Ah, last versions of LilyTexturePacker are for 2.83 minimum :/
