### ISSUE TITLE
Cannot import RDC file

### ISSUE THREAD

**Issue by CondormanFr** [eliemichel/MapsModelsImporter#81]
I try several time to import my rdc file in blender without success.
I capture with delay trigger
I used chrome and vivaldi with expected parameters.
My rdc generated file is 42 Mb.
[maison.rdc (google drive)](https://drive.google.com/file/d/14yTfIZVTVAdWBlBN6lU9tusQr04TwCd6/view?usp=sharing)

Blender 2.83.6
MapsModelsImporter 0.3.1
Render doc 1.10
GTX 1080

**Comment by eliemichel** [comment]
Version 1.10 of RenderDoc (published yesterday) changed the rdc file format, use version 1.9 until I rebuild a new versionf of this add-on for 1.10.

**Comment by CondormanFr** [comment]
Thank you very much. It works great with 1.9
