### ISSUE TITLE
Cannot import RDC file

### ISSUE THREAD

**Issue by Alfwei** [eliemichel/MapsModelsImporter#82]
Hi Elie, I have trouble importing my rdc files to Blender. I have tried different locations on google map, different resolutions, but none of them worked out. 

 - [The .rdc file](https://drive.google.com/file/d/1dVOJn2ikM1s59cPylrO9l76VKp4KY6Vo/view?usp=sharing)
 - GPU Intel HD Graphics P630
 - MapsModelsImporter-v0.3.2
 - RenderDoc 1.10
 - Blender 2.90

**Comment by eliemichel** [comment]
Same as #81, I've openned #83 to follow it and in the meantime just use RenderDoc v1.9
