### ISSUE TITLE
API non détecté

### ISSUE THREAD

**Issue by amatistrad** [eliemichel/MapsModelsImporter#88]
Bonjour Elie,

Je possède un PC équipé d'une RX5700xt donc chez amd. Le problème que je rencontre, c'est que l'API ne semble pas reconnu par renderdoc, du coup l'injection n'a pas lieu et aucune capture n'est possible. J'ai bien tenté de suivre les processus comme indiqué dans les précédents tickets de github mais cela ne change rien peut importe les versions de chrome ou de renderdoc essayées. Merci d'avance pour ton aide.

**Comment by eliemichel** [comment]
Bonjour @amatistrad, as-tu bien fermé tous les processus Chrome avant de lancer le raccourci personnalisé pour RenderDoc ?
Si oui, à ce stade le mieux pour que je puisse aider serait un enregistrement vidéo d'une tentative de capture !

**Comment by amatistrad** [comment]
Merci pour ta réponse, j'ai fait une petite vidéo. Comment je te l'envoies? Merci pour ton aide en tout cas.

**Comment by eliemichel** [comment]
Un lien dropbox ou wetransfer par exemple (tu peux wetransfer à toi-même et mettre le lien ici)

**Comment by amatistrad** [comment]
https://www.transfernow.net/EnNx4v092020
Voici le lien merci.

**Comment by eliemichel** [comment]
Il faut utiliser un lien modifié vers chrome, qui contienne dans la cible :

```
C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog"
```

**Comment by amatistrad** [comment]
Super ça marche merci!!!
