### ISSUE TITLE
Invalid RDC capture file.

### ISSUE THREAD

**Issue by dusoethe** [eliemichel/MapsModelsImporter#90]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file
https://drive.google.com/file/d/1k4GgG1HIotyfTdzQQQ7XZQHliu4P1jzw/view?usp=sharing

 - Your GPU name
AMD Radeon(TM) R9 290X

 - Version of this add-on (must be the most recent one)
0.3.1
 - Version of RenderDoc (1.6 recommended)
Latest Release: v1.10 - 18 Sep, 2020
 - Version of Blender (2.82 recommended)
Blender 2.90.1

I used it in the past a few times, now it has the update, I did it and it is no longer working, I uninstalled everything and reinstalled and it remains the same

**Comment by eliemichel** [comment]
Don't use RenderDoc v1.10, downgrade to v1.9 for the moment. See #83 for follow ups!

**Comment by dusoethe** [comment]
ITS WORKING NOW.
THANKS!!

Em ter., 29 de set. de 2020 às 12:47, Elie Michel <notifications@github.com>
escreveu:
