### ISSUE TITLE
Cant impord RDC file

### ISSUE THREAD

**Issue by ThomasMulligan123** [eliemichel/MapsModelsImporter#91]
I can capture and save the rdc file and see it when importing, but it refuses to import into blender, I get a invalid capture file. I also noticed (I dont know if its a factor) When I open Chrome in debug mode and get the numerical code I don't get the console text on top of the toolbar when closed, but it opens normally. I can still capture google maps and save within Render Doc.
Console in blender reads:
Read prefs: C:\Users\1tomm\AppData\Roaming\Blender Foundation\Blender\2.90\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.90\2.90\python

**Comment by eliemichel** [comment]
Do you use RenderDoc v1.10? If so, downgrade to v1.9 (see #83)

**Comment by ThomasMulligan123** [comment]
I do I'll downgrade so and see what happens. Cheers

**Comment by ThomasMulligan123** [comment]
Cheers buddy I'm up and running. it Imported first go. thanks for your expertise and prompt reply.
