### ISSUE TITLE
fyi download from release page does work with blender2.83 but not with blender2.9

### ISSUE THREAD

**Issue by krz9000** [eliemichel/MapsModelsImporter#93]
needs admin rights to install with blender2.9 in case the addon does not appear (install works for blender2.83 without admin rights)

this is just ment as an additional information for people that have trouble installing the addon. its not this addons fault that its this way

**Comment by eliemichel** [comment]
Do you have both version of Blender installed at the same location on your system directories?

**Comment by krz9000** [comment]
yes they sit next to each other in program files...but i dont remember my blender install settings. i think this "issue" is purely on my side..and only helps people that have similar issues by considering running as admin if the addon might not install for them.
