### ISSUE TITLE
Cannot import the .rdc file

### ISSUE THREAD

**Issue by rajeshroy402** [eliemichel/MapsModelsImporter#94]
Hello,
I properly follow this video: https://youtu.be/F_XsmoZJmG8 but still it is giving me error that the either I should use Google Map instead of Google earth and the another one that I should move the map while turning on immediate capture. I'm using Blender 2.9.1 and renderdoc 1.10
Kindly help me!

**Comment by eliemichel** [comment]
Downgrade RenderDoc to v1.9, see #83
