### ISSUE TITLE
Error in installation for Blender 2.79b

### ISSUE THREAD

**Issue by rajeshroy402** [eliemichel/MapsModelsImporter#95]
![image](https://user-images.githubusercontent.com/40631866/95184151-980f2780-07e4-11eb-98a4-efbbb24f1abf.png)

I'm getting this error for Blender 2.79b

**Comment by eliemichel** [comment]
Any strong reason to use such an outdated version of Blender ? The long term support one is 2.83.

**Comment by rajeshroy402** [comment]
Yes. I want to develop a simulation using Webots. I want to use Blender to create the environment and then want to export it to .wbt file [Add on repo](https://github.com/cyberbotics/blender-webots-exporter) which supports 2.79

**Comment by eliemichel** [comment]
Interesting, to be honest I think it would be more straightforward to port the wbt exporter to Blender 2.8 than to backport this to 2.79!

**Comment by eliemichel** [comment]
@rajeshroy402 sorry but I cannot afford to maintain this for a version as old as Blender 2.79, closing this then!
