### ISSUE TITLE
As of today my RenderDoc is no longer showing the overlay on Chrome

### ISSUE THREAD

**Issue by taserak** [eliemichel/MapsModelsImporter#97]
Yesterday I was able to snag a few captures and import them into Blender successfully.

Today however, Render Doc does not show the text overlay, and also lists API as none.
I am not sure what changed, as a test I installed a slightly older version of RenderDoc, but the same issue persisted.

Any help or suggestions would be appreciated.

**Comment by dellisd** [comment]
I was able to get this to work with Edge instead of Chrome.

**Comment by taserak** [comment]
> I was able to get this to work with Edge instead of Chrome.

Sweet, How do I do it with Edge? 

I use a modified shortcut to connect to chrome, I am not sure how to do it with Edge.

**Comment by JarekB** [comment]
Do you use the same flags as Chrome shortcut? I'd like to try with Edge as well since had no luck with injecting the process to Chrome, even with trying multiple older versions.

**Comment by dellisd** [comment]
Yeah, I had pretty much the exact same setup but with the Edge executable instead. (this is new Edge, of course).

```
"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --disable-gpu-sandbox --gpu-startup-dialog
```

**Comment by JarekB** [comment]
thanks, it makes Edge show the same GPU popup; yet I still can't make the injection work... so the problem must be not browser-specific. Which version of the RenderDoc are you using? 
I also wonder if it matters if the system has 2 GPU (I have Intel built-in and NVidia GeForce).

**Comment by dellisd** [comment]
I was using RenderDoc 1.9.

**Comment by eliemichel** [comment]
@JarekB If you have multiple GPUs make sure chrome/edge and renderdoc are running on the same one
@dellisd Neat, didn't know it was working exactly the same on edge

I've had a few reports about the injection no longer working with chrome but did not experience it myself, I don't know if something really happend.

**Comment by taserak** [comment]
@eliemichel 

> If you have multiple GPUs make sure chrome/edge and renderdoc are running on the same one

This my be the cause, the comp im using seems to have Intel built-in and NVidia GeForce too,
But I still cant get it to work, my attempts to have them on the same GPU don't seems to have an effect.

I was also not able to get Edge to work either, I don't seem to have an executable file I can shortcut to. or at least I can't find it.

**Comment by dellisd** [comment]
Do you have the new chromium-based Edge installed?

I also wonder if a build of plain old Chromium (or other chromium-based browsers) would work.

**Comment by eliemichel** [comment]
On my system it is located at `C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe` (iterate "right click > open file location "on the Start Menu entry). I can confirm it works by the way, don't forget the `set RENDERDOC_HOOK_EGL=0`.

@taserak Could you maybe screen record your attempt so we can troubleshot it more finely?

**Comment by bhaktatejas922** [comment]
Same issue here. Works on edge canary (version 88) but not latest stable chrome (verions 86)

**Comment by bhaktatejas922** [comment]
I'm thinking its possible google caught wind of this and saw it as a security issue for the stable chrome releases?

**Comment by eliemichel** [comment]
No if there is an issue in the new version confirmed (which I'm not experimenting myself by the way) it'll just require an update of the process but unless they start rendering the 3D for everybody on their server there will always be a way. Proof is it still works with edge, and they cannot prevent one from installing older versions of Chromium.

**Comment by eliemichel** [comment]
25 days later, it seems that people are still well able to follow the process, so I am closing this now!
